// dsh-themes — browser half (client plugin bundle). GENERATED FILE:
// run `node scripts/gen-themes.mjs` to regenerate from lib/client.tpl.js.
//
// Loaded by dsh-client-modules at /plugins/dsh-themes/client.js and
// executed through the vendored cordis Loader's lazy-CJS module table
// (window.__ModuleLoader__.load). The factory body is plain CJS with
// require() resolved against the shell's module table — the same shape the
// shipped ui-* packages' bundles emit.
//
// Structure modeled on zhijun-dai/Catppuccin-dsh-theme (MIT).
window.__ModuleLoader__.load({
  id: "dsh-themes",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    let react_jsx_runtime = require("react/jsx-runtime");
    let _runtime_client = require("@deepseek-ai/dsh-client-runtime/client");

    //#region dsh-themes: definitions
    /** The settings row's locale namespace. */
    const SETTINGS_NS = "settings.themes";
    /** localStorage key holding the meta preference `{family, mode}`. */
    const STORAGE_KEY = "dsh-themes:pref";
    /** Selectable modes; "system" follows the OS color scheme. */
    const MODES = ["light", "dark", "system"];

    /**
     * The theme pack catalog, generated by scripts/gen-themes.mjs from
     * families/*.mjs: `[{ id, names: { zh, en }, skins: [light, dark] }]`.
     * Each skin is a third-party theme for the built-in ThemeRuntime: an
     * id (`<family>-<mode>`), the colorScheme driving
     * body[data-ds-dark-theme], and --dsw-* overrides applied as inline
     * custom properties by ui-layout's ThemePresenter. Family ids must not
     * contain "-light"/"-dark" suffixes themselves.
     */
    const CATALOG = __CATALOG__;

    /** All skins of all families, flat — what gets registered. */
    const SKINS = CATALOG.flatMap((family) => family.skins);

    /**
     * Parse a runtime preference into { family, colorScheme } if it names
     * one of this pack's skins, else null.
     */
    function parseSkin(preference) {
      for (const family of CATALOG) {
        if (preference === `${family.id}-light`) return { family: family.id, colorScheme: "light" };
        if (preference === `${family.id}-dark`) return { family: family.id, colorScheme: "dark" };
      }
      return null;
    }

    /** Simplified Chinese dictionary (the key-set source of truth). */
    const zh = {
      "theme.title": "主题",
      "theme.default": "默认",
      "mode.light": "浅色",
      "mode.dark": "深色",
      "mode.system": "跟随系统"
    };

    /** English dictionary, checked complete against the zh key set. */
    const en = {
      "theme.title": "Themes",
      "theme.default": "Default",
      "mode.light": "Light",
      "mode.dark": "Dark",
      "mode.system": "System"
    };

    // Family display names come from the catalog data, not from code.
    for (const family of CATALOG) {
      zh[`family.${family.id}`] = family.names.zh;
      en[`family.${family.id}`] = family.names.en;
    }
    //#endregion

    //#region dsh-themes: meta preference (family × mode, with system follow)
    /** The OS color scheme, watched so "system" mode can follow it. */
    const darkQuery = window.matchMedia("(prefers-color-scheme: dark)");

    /**
     * The runtime preference is a single skin id — it has no notion of
     * "this family, follow the OS". The pack therefore persists a meta
     * preference `{family, mode}` and translates it into a concrete skin
     * id whenever it is applied: mode "system" resolves against the
     * current OS scheme, and the translation is re-run on every scheme
     * flip (see the darkQuery listener in apply).
     */
    function resolveSkin(pref) {
      if (!pref) return null;
      const mode = pref.mode === "system" ? (darkQuery.matches ? "dark" : "light") : pref.mode;
      return `${pref.family}-${mode}`;
    }

    /** Read the stored meta preference (null on absence/garbage/unknown). */
    function readPref() {
      try {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (typeof raw !== "string") return null;
        const parsed = JSON.parse(raw);
        if (
          parsed &&
          typeof parsed.family === "string" &&
          MODES.includes(parsed.mode) &&
          CATALOG.some((family) => family.id === parsed.family)
        ) {
          return { family: parsed.family, mode: parsed.mode };
        }
        return null;
      } catch {
        return null;
      }
    }

    /** Persist a meta preference; null clears the stored value. */
    function writePref(pref) {
      try {
        if (pref === null) window.localStorage.removeItem(STORAGE_KEY);
        else window.localStorage.setItem(STORAGE_KEY, JSON.stringify(pref));
      } catch {
        // storage unavailable / quota — the preference stays process-local
      }
    }
    //#endregion

    //#region dsh-themes: settings row store
    /**
     * Settings-row slot store: `{family, mode}` as derived from the theme
     * service snapshot plus the stored meta preference. The plugin's
     * apply-world change listener is the only writer; the row component
     * reads via props.useStore.
     */
    function createPrefStore() {
      return (0, _runtime_client.defineStore)({
        init: () => ({
          family: null,
          mode: "system",
          revision: -1
        }),
        actions: {
          sync: (d, family, mode, revision) => {
            if (revision <= d.revision) return;
            d.family = family;
            d.mode = mode;
            d.revision = revision;
          }
        }
      });
    }
    //#endregion

    //#region dsh-themes: settings row
    /** Inline style sheet for the row (kept dependency-free). */
    const styles = {
      group: {
        borderBottom: "1px solid var(--dsw-alias-border-l2)",
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        padding: "16px 0"
      },
      title: {
        color: "var(--dsw-alias-label-primary)",
        fontSize: "14px",
        fontWeight: 400,
        lineHeight: "22px"
      },
      grid: {
        display: "flex",
        flexWrap: "wrap",
        gap: "10px"
      },
      card: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "6px",
        width: "96px",
        padding: "3px",
        borderRadius: "10px",
        // longhand on purpose: the shorthand leaves borderColor to
        // fall back to currentColor once React clears the selected
        // override, painting stale black/white boxes on deselect
        borderWidth: "2px",
        borderStyle: "solid",
        borderColor: "transparent",
        background: "transparent",
        cursor: "pointer",
        font: "inherit",
        boxSizing: "border-box"
      },
      cardSelected: {
        borderColor: "var(--dsw-alias-brand-primary)",
        background: "var(--dsw-alias-interactive-bg-hover)"
      },
      cardLabel: {
        color: "var(--dsw-alias-label-secondary)",
        fontSize: "12px",
        lineHeight: "16px",
        whiteSpace: "nowrap"
      },
      cardLabelSelected: {
        color: "var(--dsw-alias-label-primary)"
      },
      splitSwatch: {
        width: "100%",
        height: "52px",
        borderRadius: "8px",
        boxSizing: "border-box",
        display: "flex",
        overflow: "hidden",
        border: "1px solid var(--dsw-alias-border-l2)"
      },
      swatchHalf: {
        flex: 1,
        padding: "8px 6px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        gap: "6px"
      },
      swatchLine: {
        height: "6px",
        borderRadius: "3px"
      },
      chips: {
        display: "flex",
        flexWrap: "wrap",
        gap: "8px"
      },
      chip: {
        padding: "4px 12px",
        borderRadius: "999px",
        // longhand, same reason as the card border
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "var(--dsw-alias-border-l2)",
        background: "transparent",
        color: "var(--dsw-alias-label-secondary)",
        fontSize: "12px",
        lineHeight: "16px",
        cursor: "pointer",
        font: "inherit",
        boxSizing: "border-box"
      },
      chipSelected: {
        borderColor: "var(--dsw-alias-brand-primary)",
        color: "var(--dsw-alias-brand-primary)",
        background: "var(--dsw-alias-interactive-bg-hover-accent)"
      }
    };

    /** One half of a family swatch: the skin's ground with text + brand stripes. */
    function SwatchHalf({ tokens }) {
      return (0, react_jsx_runtime.jsxs)("div", {
        style: {
          ...styles.swatchHalf,
          background: tokens["--dsw-alias-bg-layer-1"]
        },
        children: [
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "75%",
              background: tokens["--dsw-alias-label-primary"],
              opacity: 0.85
            }
          }),
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "55%",
              background: tokens["--dsw-alias-brand-primary"]
            }
          })
        ]
      });
    }

    /** Family preview: light skin on the left half, dark on the right. */
    function FamilySwatch({ family }) {
      const light = family.skins.find((skin) => skin.colorScheme === "light");
      const dark = family.skins.find((skin) => skin.colorScheme === "dark");
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.splitSwatch,
        children: [
          (0, react_jsx_runtime.jsx)(SwatchHalf, { tokens: light.tokens }),
          (0, react_jsx_runtime.jsx)(SwatchHalf, { tokens: dark.tokens })
        ]
      });
    }

    /** "Default" chip: follow the built-in appearance (light + dark halves). */
    function DefaultSwatch() {
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.splitSwatch,
        children: [
          (0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#f4f4f5" } }),
          (0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#1c1c20" } })
        ]
      });
    }

    /** One selectable family card. */
    function FamilyCard({ family, selected, onSelect, t }) {
      return (0, react_jsx_runtime.jsxs)("button", {
        type: "button",
        onClick: (event) => {
          onSelect();
          // drop focus so a stale focus ring never outlives the selection
          event.currentTarget.blur();
        },
        "aria-pressed": selected,
        style: {
          ...styles.card,
          ...(selected ? styles.cardSelected : {})
        },
        children: [
          (0, react_jsx_runtime.jsx)(FamilySwatch, { family }),
          (0, react_jsx_runtime.jsx)("span", {
            style: {
              ...styles.cardLabel,
              ...(selected ? styles.cardLabelSelected : {})
            },
            children: t(`family.${family.id}`)
          })
        ]
      });
    }

    /** One mode chip (light / dark / system). */
    function ModeChip({ label, selected, onSelect }) {
      return (0, react_jsx_runtime.jsx)("button", {
        type: "button",
        onClick: (event) => {
          onSelect();
          event.currentTarget.blur();
        },
        "aria-pressed": selected,
        style: {
          ...styles.chip,
          ...(selected ? styles.chipSelected : {})
        },
        children: label
      });
    }

    /**
     * The pack's single settings row, registered into the Settings →
     * General item slot: a family card grid (Default + one per family)
     * and, once a family is chosen, the mode chips — light / dark /
     * follow-system.
     */
    function ThemeRow({ t, selectFamily, selectMode, useStore }) {
      const family = useStore((s) => s.family);
      const mode = useStore((s) => s.mode);
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.group,
        children: [
          (0, react_jsx_runtime.jsx)("div", {
            style: styles.title,
            children: t("theme.title")
          }),
          (0, react_jsx_runtime.jsxs)("div", {
            style: styles.grid,
            children: [
              (0, react_jsx_runtime.jsxs)("button", {
                type: "button",
                onClick: (event) => {
                  selectFamily(null);
                  event.currentTarget.blur();
                },
                "aria-pressed": family === null,
                style: {
                  ...styles.card,
                  ...(family === null ? styles.cardSelected : {})
                },
                children: [
                  (0, react_jsx_runtime.jsx)(DefaultSwatch, {}),
                  (0, react_jsx_runtime.jsx)("span", {
                    style: {
                      ...styles.cardLabel,
                      ...(family === null ? styles.cardLabelSelected : {})
                    },
                    children: t("theme.default")
                  })
                ]
              }),
              CATALOG.map((familyDefinition) => (0, react_jsx_runtime.jsx)(FamilyCard, {
                family: familyDefinition,
                selected: family === familyDefinition.id,
                onSelect: () => selectFamily(familyDefinition.id),
                t
              }, familyDefinition.id))
            ]
          }),
          family === null
            ? null
            : (0, react_jsx_runtime.jsx)("div", {
                style: styles.chips,
                children: MODES.map((modeId) => (0, react_jsx_runtime.jsx)(ModeChip, {
                  label: t(`mode.${modeId}`),
                  selected: mode === modeId,
                  onSelect: () => selectMode(modeId)
                }, modeId))
              })
        ]
      });
    }
    //#endregion

    //#region dsh-themes: client plugin body
    /**
     * Required services: theme runtime (skins, switching), slots/locale
     * (the settings row). Persistence is localStorage, so no settings
     * transport is needed.
     */
    const inject = [
      "slots",
      "locale",
      "theme"
    ];

    /**
     * Client plugin body: register every skin into the theme runtime,
     * restore the saved meta preference (translating "system" against the
     * OS scheme and following its flips), keep the row's store in sync
     * with theme/change, and register the picker into Settings → General.
     * @param ctx - client cordis context.
     */
    function apply(ctx) {
      const disposers = SKINS.map((skinDefinition) => ctx.theme.register(skinDefinition));
      ctx.effect(() => () => {
        for (const dispose of disposers) dispose();
      }, "dsh-themes: theme registration");

      // Minimal surface tint: the user-message bubble carries a brand wash
      // so the two roles read apart; assistant replies intentionally stay
      // on the bare canvas. Message reference chips follow the brand. The
      // rules reference --dsw-pack-accent, which every skin in the pack
      // defines, so they work unchanged for every family. Keyed on stable
      // CSS-module suffixes.
      //
      // Every selector is boosted with :not(#dsh-themes): the shipped ui-*
      // stylesheets are injected by React after ours, so a plain attribute
      // selector loses to the equally specific module class and the tint
      // silently dies. The :not(id) pseudo is a no-op predicate that only
      // raises specificity.
      //
      // The sheet is mounted only while one of the pack's skins is active
      // and removed on the "Default" preference, so the built-in
      // appearance stays pixel-identical unless the user picked a family.
      // Hashed class suffixes can shift between harness versions — keep
      // this list short on purpose.
      const boost = (selector) =>
        selector.split(",").map((part) => `${part.trim()}:not(#dsh-themes)`).join(",");
      const SURFACE_RULES = [
        // user bubble: brand wash over the layer-2 surface, stronger on
        // dark skins where the ground is deep
        [
          '[class$="_userStack"] [class$="_bubble"]',
          " background: color-mix(in srgb, var(--dsw-pack-accent) 30%, var(--dsw-alias-bg-layer-2));"
        ],
        // body[data-ds-dark-theme] is present on dark schemes only: light
        // skins tint at 16% so the pale wash stays quiet
        [
          'body:not([data-ds-dark-theme]) [class$="_userStack"] [class$="_bubble"]',
          " background: color-mix(in srgb, var(--dsw-pack-accent) 16%, var(--dsw-alias-bg-layer-2));"
        ],
        // message reference chips: recolor from the brand
        [
          '[class$="_refChip"]',
          " background: color-mix(in srgb, var(--dsw-alias-brand-primary) 22%, transparent);"
        ]
      ].map(([selector, body]) => `${boost(selector)} {\n${body}\n}`).join("\n");
      const style = document.createElement("style");
      style.textContent = SURFACE_RULES;
      const syncSurfaceTint = () => {
        const active = parseSkin(ctx.theme.getTheme().preference) !== null;
        if (active && !style.isConnected) document.head.appendChild(style);
        if (!active && style.isConnected) style.remove();
      };
      syncSurfaceTint();
      ctx.on("theme/change", syncSurfaceTint);
      ctx.effect(() => () => {
        style.remove();
      }, "dsh-themes: surface tint lifecycle");

      // Restore the saved meta preference. The ThemeService adopts its
      // durable built-in preference ("light"/"dark"/"system") from the
      // Host settings scope asynchronously after boot, which overwrites a
      // third-party preference restored too early. Re-assert the resolved
      // skin for a short boot window (a handful of change events or a few
      // seconds), then yield to subsequent user actions.
      let bootGuard = readPref() ? 3 : 0;
      const reassertSaved = () => {
        if (bootGuard <= 0) return;
        const target = resolveSkin(readPref());
        if (target === null) return;
        if (ctx.theme.getTheme().preference === target) return;
        bootGuard -= 1;
        ctx.theme.setTheme(target);
      };
      reassertSaved();
      const bootWindow = setTimeout(() => {
        bootGuard = 0;
      }, 5000);
      ctx.effect(() => () => {
        clearTimeout(bootWindow);
      }, "dsh-themes: boot restore window");

      // Follow the OS color scheme while the stored mode is "system":
      // re-translate the meta preference into a concrete skin on every
      // flip. Explicit light/dark modes are pinned and ignore this.
      const onSchemeChange = () => {
        const stored = readPref();
        if (stored && stored.mode === "system") {
          ctx.theme.setTheme(resolveSkin(stored));
        }
      };
      darkQuery.addEventListener("change", onSchemeChange);
      ctx.effect(() => () => {
        darkQuery.removeEventListener("change", onSchemeChange);
      }, "dsh-themes: color-scheme listener");

      const prefStore = createPrefStore();
      let storeBound;
      const syncStore = (snapshot) => {
        const parsed = parseSkin(snapshot.preference);
        const stored = readPref();
        const family = parsed ? parsed.family : null;
        const mode = parsed
          ? stored && stored.family === parsed.family
            ? stored.mode
            : parsed.colorScheme
          : "system";
        storeBound?.sync(family, mode, snapshot.revision);
      };
      ctx.on("theme/change", (snapshot) => {
        const preference = snapshot.preference;
        const stored = readPref();
        const parsed = parseSkin(preference);
        if (parsed && preference !== resolveSkin(stored)) {
          // One of the pack's skins became active without matching the
          // stored meta preference (picked through another entry point):
          // adopt it as an explicit light/dark choice.
          writePref({ family: parsed.family, mode: parsed.colorScheme });
        } else if (!parsed && preference !== "light" && preference !== "dark" && preference !== "system") {
          // Another plugin's third-party theme took over: drop our stored
          // preference so only the last-picked plugin restores at boot
          // (both plugins must implement this convention).
          writePref(null);
        }
        syncStore(snapshot);
        // Re-assert from a fresh task: a re-entrant setTheme inside the
        // dispatch is missed by other subscribers (ui-layout's
        // ThemePresenter), so the restored skin would never reach the DOM.
        setTimeout(() => {
          reassertSaved();
        }, 0);
      });

      ctx.effect(() => ctx.locale.register(SETTINGS_NS, {
        zh,
        en
      }), "dsh-themes: settings row dictionaries");

      const themeInjected = (actions) => {
        storeBound = actions;
        syncStore(ctx.theme.getTheme());
        return {
          selectFamily: (familyId) => {
            if (familyId === null) {
              // Default: hand appearance back to the built-in light/dark/
              // system handling, natively following the OS.
              writePref(null);
              ctx.theme.setTheme("system");
              return;
            }
            // A freshly picked family starts in follow-system mode.
            const stored = readPref();
            const pref = {
              family: familyId,
              mode: stored && stored.family === familyId ? stored.mode : "system"
            };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          },
          selectMode: (mode) => {
            const stored = readPref();
            if (!stored) return;
            const pref = { family: stored.family, mode };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          }
        };
      };
      ctx.slots.inject("settings.general.item", () => ctx.slots.register({
        name: "settings.general.item",
        id: "themes",
        order: 19,
        store: prefStore,
        locale: SETTINGS_NS,
        inject: themeInjected
      }, ThemeRow));
    }
    //#endregion

    exports.CATALOG = CATALOG;
    exports.SKINS = SKINS;
    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
