// dsh-themes — browser half (client plugin bundle). GENERATED FILE:
// run `node scripts/gen-themes.mjs` to regenerate from lib/client.tpl.js.
//
// Loaded by dsh-client-modules at /plugins/dsh-themes/client.js and
// executed through the vendored cordis Loader's lazy-CJS module table
// (window.__ModuleLoader__.load). The factory body is plain CJS with
// require() resolved against the shell's module table — the same shape the
// shipped ui-* packages' bundles emit.
//
// Structure modeled on zhijun-dai/Catppuccin-dsh-theme (MIT).
window.__ModuleLoader__.load({
  id: "dsh-themes",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    let react_jsx_runtime = require("react/jsx-runtime");
    let _runtime_client = require("@deepseek-ai/dsh-client-runtime/client");

    //#region dsh-themes: definitions
    /** The settings row's locale namespace. */
    const SETTINGS_NS = "settings.themes";
    /** localStorage key holding the meta preference `{family, mode}`. */
    const STORAGE_KEY = "dsh-themes:pref";
    /** Selectable modes; "system" follows the OS color scheme. */
    const MODES = ["light", "dark", "system"];

    /**
     * The theme pack catalog, generated by scripts/gen-themes.mjs from
     * families/*.mjs: `[{ id, names: { zh, en }, skins: [light, dark] }]`.
     * Each skin is a third-party theme for the built-in ThemeRuntime: an
     * id (`<family>-<mode>`), the colorScheme driving
     * body[data-ds-dark-theme], and --dsw-* overrides applied as inline
     * custom properties by ui-layout's ThemePresenter. Family ids must not
     * contain "-light"/"-dark" suffixes themselves.
     */
    const CATALOG = [
      {
        "id": "chainsaw",
        "names": {
          "zh": "电锯人",
          "en": "Chainsaw Man"
        },
        "skins": [
          {
            "id": "chainsaw-light",
            "name": "Chainsaw Man Light",
            "colorScheme": "light",
            "tokens": {
              "--dsw-static-neutral-bluish-50": "color-mix(in srgb, #F4EFE4 50%, #E7E0D1)",
              "--dsw-static-neutral-50": "color-mix(in srgb, #F4EFE4 50%, #E7E0D1)",
              "--dsw-static-neutral-bluish-60": "#E7E0D1",
              "--dsw-static-neutral-60": "#E7E0D1",
              "--dsw-static-neutral-bluish-75": "color-mix(in srgb, #E7E0D1 50%, #CFC6B3)",
              "--dsw-static-neutral-75": "color-mix(in srgb, #E7E0D1 50%, #CFC6B3)",
              "--dsw-static-neutral-bluish-100": "#CFC6B3",
              "--dsw-static-neutral-100": "#CFC6B3",
              "--dsw-static-neutral-bluish-150": "color-mix(in srgb, #CFC6B3 50%, #BEB4A0)",
              "--dsw-static-neutral-150": "color-mix(in srgb, #CFC6B3 50%, #BEB4A0)",
              "--dsw-static-neutral-bluish-200": "#BEB4A0",
              "--dsw-static-neutral-200": "#BEB4A0",
              "--dsw-static-neutral-bluish-250": "color-mix(in srgb, #BEB4A0 50%, #A79D8B)",
              "--dsw-static-neutral-250": "color-mix(in srgb, #BEB4A0 50%, #A79D8B)",
              "--dsw-static-neutral-bluish-300": "#A79D8B",
              "--dsw-static-neutral-300": "#A79D8B",
              "--dsw-static-neutral-bluish-400": "color-mix(in srgb, #A79D8B 50%, #7D7466)",
              "--dsw-static-neutral-400": "color-mix(in srgb, #A79D8B 50%, #7D7466)",
              "--dsw-static-neutral-bluish-500": "#7D7466",
              "--dsw-static-neutral-500": "#7D7466",
              "--dsw-static-neutral-bluish-550": "color-mix(in srgb, #7D7466 50%, #6B6256)",
              "--dsw-static-neutral-550": "color-mix(in srgb, #7D7466 50%, #6B6256)",
              "--dsw-static-neutral-bluish-600": "#6B6256",
              "--dsw-static-neutral-600": "#6B6256",
              "--dsw-static-neutral-bluish-700": "color-mix(in srgb, #6B6256 50%, #585044)",
              "--dsw-static-neutral-700": "color-mix(in srgb, #6B6256 50%, #585044)",
              "--dsw-static-neutral-bluish-750": "#585044",
              "--dsw-static-neutral-750": "#585044",
              "--dsw-static-neutral-bluish-800": "color-mix(in srgb, #585044 50%, #463F35)",
              "--dsw-static-neutral-800": "color-mix(in srgb, #585044 50%, #463F35)",
              "--dsw-static-neutral-bluish-850": "#463F35",
              "--dsw-static-neutral-850": "#463F35",
              "--dsw-static-neutral-bluish-875": "color-mix(in srgb, #463F35 50%, #332C24)",
              "--dsw-static-neutral-875": "color-mix(in srgb, #463F35 50%, #332C24)",
              "--dsw-static-neutral-bluish-900": "#332C24",
              "--dsw-static-neutral-900": "#332C24",
              "--dsw-static-neutral-bluish-950": "color-mix(in srgb, #332C24 50%, #28221B)",
              "--dsw-static-neutral-950": "color-mix(in srgb, #332C24 50%, #28221B)",
              "--dsw-static-neutral-bluish-1000": "#28221B",
              "--dsw-static-neutral-1000": "#28221B",
              "--dsw-static-neutral-bluish-00": "#F4EFE4",
              "--dsw-static-neutral-00": "#F4EFE4",
              "--dsw-static-deepseek-50": "color-mix(in srgb, #C24A00 60%, #F4EFE4)",
              "--dsw-static-deepseek-100": "color-mix(in srgb, #C24A00 40%, #F4EFE4)",
              "--dsw-static-deepseek-200": "#EE8F4D",
              "--dsw-static-deepseek-300": "color-mix(in srgb, #C24A00 75%, #F4EFE4)",
              "--dsw-static-deepseek-400": "#C24A00",
              "--dsw-static-deepseek-450": "#C24A00",
              "--dsw-static-deepseek-500": "#C24A00",
              "--dsw-static-deepseek-600": "color-mix(in srgb, #C24A00 65%, #332C24)",
              "--dsw-static-deepseek-800": "color-mix(in srgb, #C24A00 30%, #332C24)",
              "--dsw-static-deepseek-900": "color-mix(in srgb, #C24A00 18%, #332C24)",
              "--dsw-static-deepseek-700-delete": "color-mix(in srgb, #C24A00 45%, #332C24)",
              "--dsw-static-blue-50": "color-mix(in srgb, #B5470F 55%, #F4EFE4)",
              "--dsw-static-blue-75": "color-mix(in srgb, #B5470F 35%, #F4EFE4)",
              "--dsw-static-blue-100": "color-mix(in srgb, #B5470F 28%, #F4EFE4)",
              "--dsw-static-blue-300": "color-mix(in srgb, #B5470F 78%, #F4EFE4)",
              "--dsw-static-blue-400": "color-mix(in srgb, #B5470F 88%, #F4EFE4)",
              "--dsw-static-blue-450": "#C24A00",
              "--dsw-static-blue-500": "#C24A00",
              "--dsw-static-blue-600": "color-mix(in srgb, #B5470F 70%, #332C24)",
              "--dsw-static-blue-800": "color-mix(in srgb, #B5470F 50%, #332C24)",
              "--dsw-static-blue-900": "color-mix(in srgb, #B5470F 35%, #332C24)",
              "--dsw-static-blue-950": "color-mix(in srgb, #B5470F 25%, #332C24)",
              "--dsw-static-blue-50p": "color-mix(in srgb, #B5470F 48%, #F4EFE4)",
              "--dsw-static-green-100": "color-mix(in srgb, #4A7C3A 35%, #F4EFE4)",
              "--dsw-static-green-400": "color-mix(in srgb, #4A7C3A 80%, #F4EFE4)",
              "--dsw-static-green-500": "#4A7C3A",
              "--dsw-static-green-900": "color-mix(in srgb, #4A7C3A 35%, #332C24)",
              "--dsw-static-red-50": "color-mix(in srgb, #B11E23 45%, #F4EFE4)",
              "--dsw-static-red-100": "color-mix(in srgb, #B11E23 28%, #F4EFE4)",
              "--dsw-static-red-400": "color-mix(in srgb, #B11E23 78%, #F4EFE4)",
              "--dsw-static-red-500": "#B11E23",
              "--dsw-static-red-600": "color-mix(in srgb, #B11E23 68%, #332C24)",
              "--dsw-static-red-900": "color-mix(in srgb, #B11E23 35%, #332C24)",
              "--dsw-static-amber-100": "color-mix(in srgb, #D99A0F 35%, #F4EFE4)",
              "--dsw-static-amber-400": "color-mix(in srgb, #D99A0F 88%, #F4EFE4)",
              "--dsw-static-amber-500": "#C98A04",
              "--dsw-static-amber-600": "#C98A04",
              "--dsw-static-amber-900": "color-mix(in srgb, #C98A04 40%, #332C24)",
              "--dsw-csm-orange": "#C24A00",
              "--dsw-csm-red": "#B11E23",
              "--dsw-csm-gold": "#D99A0F",
              "--dsw-csm-cream": "#F4EFE4",
              "--dsw-pack-accent": "#C24A00",
              "--dsw-pack-accent-soft": "#EE8F4D",
              "--dsw-alias-bg-base": "#F4EFE4",
              "--dsw-alias-bg-layer-1": "#F4EFE4",
              "--dsw-alias-bg-layer-2": "#E7E0D1",
              "--dsw-alias-bg-layer-3": "#CFC6B3",
              "--dsw-alias-bg-overlay": "#F4EFE4",
              "--dsw-alias-bg-mask-1": "rgba(216, 207, 188, 0.24)",
              "--dsw-alias-bg-mask-2": "rgba(216, 207, 188, 0.12)",
              "--dsw-alias-bg-mask-3": "rgba(216, 207, 188, 0.48)",
              "--dsw-alias-bg-module-platform": "#E7E0D1",
              "--dsw-alias-bg-multi-select": "#E7E0D1",
              "--dsw-alias-bg-skeleton": "rgba(70, 63, 53, 0.08)",
              "--dsw-alias-border-l1": "rgba(88, 80, 68, 0.28)",
              "--dsw-alias-border-l2": "rgba(88, 80, 68, 0.45)",
              "--dsw-alias-border-l3": "rgba(88, 80, 68, 0.58)",
              "--dsw-alias-border-l4": "rgba(88, 80, 68, 0.72)",
              "--dsw-alias-label-primary": "#332C24",
              "--dsw-alias-label-secondary": "#585044",
              "--dsw-alias-label-tertiary": "#463F35",
              "--dsw-alias-label-caption": "#463F35",
              "--dsw-alias-label-dimmed": "#463F35",
              "--dsw-alias-brand-primary": "#C24A00",
              "--dsw-alias-brand-text": "#FFF4EA",
              "--dsw-alias-button-primary-hover": "#E85D04",
              "--dsw-alias-button-primary-dimmed": "#E7E0D1",
              "--dsw-alias-button-elevated-fill": "#F4EFE4",
              "--dsw-alias-button-floating-fill": "#F4EFE4",
              "--dsw-alias-button-floating-hover": "#E7E0D1",
              "--dsw-alias-button-ghost-active-border": "#BEB4A0",
              "--dsw-alias-button-ghost-active-fill": "#E7E0D1",
              "--dsw-alias-button-ghost-active-hover": "#CFC6B3",
              "--dsw-alias-state-business-primary": "#C24A00",
              "--dsw-alias-state-business-tertiary": "#E7E0D1",
              "--dsw-alias-state-error-primary": "#B11E23",
              "--dsw-alias-state-error-secondary": "#B11E23",
              "--dsw-alias-state-success-primary": "#4A7C3A",
              "--dsw-alias-state-success-secondary": "#4A7C3A",
              "--dsw-alias-state-success-tertiary": "#E7E0D1",
              "--dsw-alias-state-warn-label": "#8F6200",
              "--dsw-alias-state-warn-primary": "#B57A00",
              "--dsw-alias-state-warn-secondary": "#B57A00",
              "--dsw-alias-state-warn-tertiary": "#E7E0D1",
              "--dsw-alias-interactive-bg-hover": "rgba(70, 63, 53, 0.10)",
              "--dsw-alias-interactive-bg-active": "rgba(70, 63, 53, 0.16)",
              "--dsw-alias-interactive-bg-hover-accent": "rgba(194, 74, 0, 0.10)",
              "--dsw-alias-interactive-bg-hover-danger": "rgba(177, 30, 35, 0.06)",
              "--dsw-alias-interactive-bg-hover-solid": "#E7E0D1",
              "--dsw-alias-markdown-code-block": "#E7E0D1",
              "--dsw-alias-markdown-code-block-banner": "#E7E0D1",
              "--dsw-alias-markdown-code-segment-selected": "#F4EFE4",
              "--dsw-alias-markdown-code-segment-unselected": "#E7E0D1",
              "--dsw-alias-markdown-citation": "#E7E0D1",
              "--dsw-alias-markdown-inline-code": "#E7E0D1",
              "--dsw-alias-markdown-placeholder": "#E7E0D1",
              "--dsw-alias-markdown-tag": "#E7E0D1",
              "--dsw-alias-toast-bg": "#CFC6B3",
              "--dsw-alias-tooltip-bg": "#BEB4A0",
              "--dsw-alias-separator-primary": "rgba(194, 74, 0, 0.7)",
              "--dsw-alias-scrollbar-bg-l1": "#CFC6B3",
              "--dsw-alias-scrollbar-bg-l2": "#BEB4A0",
              "--dsw-alias-scrollbar-hover-l1": "#A79D8B",
              "--dsw-alias-scrollbar-hover-l2": "#A79D8B",
              "--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
              "--dsw-alias-bg-mask-drop": "rgba(255, 255, 255, 0.7)",
              "--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
              "--dsw-alias-border-inverted2": "rgba(0, 0, 0, 0)",
              "--dsw-alias-border-l2-darkmode-thin": "rgba(88, 80, 68, 0.35)",
              "--dsw-alias-brand-primary-invert": "#332C24",
              "--dsw-alias-brand-primary-new-colorprimary-new-color": "#C24A00",
              "--dsw-alias-button-contrast-fill": "#332C24",
              "--dsw-alias-button-info-fill": "#C24A00",
              "--dsw-alias-button-info-hover": "#E87A2E",
              "--dsw-alias-button-primary-fill": "#C24A00",
              "--dsw-alias-button-tool-bar-fill": "rgba(88, 80, 68, 0.5)",
              "--dsw-alias-button-tool-bar-fill-invisible": "rgba(88, 80, 68, 0.36)",
              "--dsw-alias-button-tool-bar-hover": "rgba(107, 98, 86, 0.6)",
              "--dsw-alias-label-primary-bluish": "#332C24",
              "--dsw-alias-label-primary-dimmed": "#585044",
              "--dsw-alias-label-primary-foreground": "#F4EFE4",
              "--dsw-alias-label-primary-inverted": "#F4EFE4",
              "--dsw-specific-sidebar-fill": "#E7E0D1",
              "--dsw-specific-sidebar-nav-item-active": "#BEB4A0",
              "--dsw-specific-sidebar-nav-item-active-accent": "rgba(194, 74, 0, 0.2)",
              "--dsw-specific-sidebar-nav-item-hover": "#CFC6B3",
              "--dsw-specific-bubble": "#E7E0D1",
              "--dsw-specific-bubble-highlight": "#CFC6B3",
              "--dsw-specific-input-major": "#F4EFE4",
              "--dsw-specific-login-input": "#E7E0D1",
              "--dsw-specific-menu": "#E7E0D1",
              "--dsw-specific-selector": "#CFC6B3",
              "--dsw-specific-tip": "#E7E0D1",
              "--shiki-foreground": "#332C24",
              "--shiki-background": "#E7E0D1",
              "--shiki-token-constant": "#8F6200",
              "--shiki-token-string": "#4A7C3A",
              "--shiki-token-comment": "#7D7466",
              "--shiki-token-keyword": "#C24A00",
              "--shiki-token-parameter": "#8A4A2B",
              "--shiki-token-function": "#9E2B25",
              "--shiki-token-string-expression": "#4A7C3A",
              "--shiki-token-punctuation": "#585044",
              "--shiki-token-link": "#B11E23"
            }
          },
          {
            "id": "chainsaw-dark",
            "name": "Chainsaw Man Dark",
            "colorScheme": "dark",
            "tokens": {
              "--dsw-static-neutral-bluish-50": "color-mix(in srgb, #EDE6DA 50%, #CFC6B8)",
              "--dsw-static-neutral-50": "color-mix(in srgb, #EDE6DA 50%, #CFC6B8)",
              "--dsw-static-neutral-bluish-60": "#CFC6B8",
              "--dsw-static-neutral-60": "#CFC6B8",
              "--dsw-static-neutral-bluish-75": "color-mix(in srgb, #CFC6B8 50%, #B5AB9C)",
              "--dsw-static-neutral-75": "color-mix(in srgb, #CFC6B8 50%, #B5AB9C)",
              "--dsw-static-neutral-bluish-100": "#B5AB9C",
              "--dsw-static-neutral-100": "#B5AB9C",
              "--dsw-static-neutral-bluish-150": "color-mix(in srgb, #B5AB9C 50%, #9B9081)",
              "--dsw-static-neutral-150": "color-mix(in srgb, #B5AB9C 50%, #9B9081)",
              "--dsw-static-neutral-bluish-200": "#9B9081",
              "--dsw-static-neutral-200": "#9B9081",
              "--dsw-static-neutral-bluish-250": "color-mix(in srgb, #9B9081 50%, #83796B)",
              "--dsw-static-neutral-250": "color-mix(in srgb, #9B9081 50%, #83796B)",
              "--dsw-static-neutral-bluish-300": "#83796B",
              "--dsw-static-neutral-300": "#83796B",
              "--dsw-static-neutral-bluish-400": "color-mix(in srgb, #83796B 50%, #5B5348)",
              "--dsw-static-neutral-400": "color-mix(in srgb, #83796B 50%, #5B5348)",
              "--dsw-static-neutral-bluish-500": "#5B5348",
              "--dsw-static-neutral-500": "#5B5348",
              "--dsw-static-neutral-bluish-550": "color-mix(in srgb, #5B5348 50%, #453E35)",
              "--dsw-static-neutral-550": "color-mix(in srgb, #5B5348 50%, #453E35)",
              "--dsw-static-neutral-bluish-600": "#453E35",
              "--dsw-static-neutral-600": "#453E35",
              "--dsw-static-neutral-bluish-700": "color-mix(in srgb, #453E35 50%, #352F28)",
              "--dsw-static-neutral-700": "color-mix(in srgb, #453E35 50%, #352F28)",
              "--dsw-static-neutral-bluish-750": "#352F28",
              "--dsw-static-neutral-750": "#352F28",
              "--dsw-static-neutral-bluish-800": "color-mix(in srgb, #352F28 50%, #1D1915)",
              "--dsw-static-neutral-800": "color-mix(in srgb, #352F28 50%, #1D1915)",
              "--dsw-static-neutral-bluish-850": "#1D1915",
              "--dsw-static-neutral-850": "#1D1915",
              "--dsw-static-neutral-bluish-875": "color-mix(in srgb, #1D1915 50%, #16110E)",
              "--dsw-static-neutral-875": "color-mix(in srgb, #1D1915 50%, #16110E)",
              "--dsw-static-neutral-bluish-900": "#16110E",
              "--dsw-static-neutral-900": "#16110E",
              "--dsw-static-neutral-bluish-950": "color-mix(in srgb, #16110E 50%, #100C0A)",
              "--dsw-static-neutral-950": "color-mix(in srgb, #16110E 50%, #100C0A)",
              "--dsw-static-neutral-bluish-1000": "#100C0A",
              "--dsw-static-neutral-1000": "#100C0A",
              "--dsw-static-neutral-bluish-00": "#EDE6DA",
              "--dsw-static-neutral-00": "#EDE6DA",
              "--dsw-static-deepseek-50": "color-mix(in srgb, #FF8A3D 55%, #EDE6DA)",
              "--dsw-static-deepseek-100": "color-mix(in srgb, #FF8A3D 35%, #EDE6DA)",
              "--dsw-static-deepseek-200": "#FFB37A",
              "--dsw-static-deepseek-300": "color-mix(in srgb, #FF8A3D 70%, #1D1915)",
              "--dsw-static-deepseek-400": "#FF8A3D",
              "--dsw-static-deepseek-450": "#FF8A3D",
              "--dsw-static-deepseek-500": "#FF8A3D",
              "--dsw-static-deepseek-600": "color-mix(in srgb, #FF8A3D 60%, #1D1915)",
              "--dsw-static-deepseek-800": "color-mix(in srgb, #FF8A3D 30%, #1D1915)",
              "--dsw-static-deepseek-900": "color-mix(in srgb, #FF8A3D 20%, #1D1915)",
              "--dsw-static-deepseek-700-delete": "color-mix(in srgb, #FF8A3D 45%, #1D1915)",
              "--dsw-static-blue-50": "color-mix(in srgb, #FF8A3D 55%, #EDE6DA)",
              "--dsw-static-blue-75": "color-mix(in srgb, #FF8A3D 35%, #EDE6DA)",
              "--dsw-static-blue-100": "color-mix(in srgb, #FF8A3D 25%, #EDE6DA)",
              "--dsw-static-blue-300": "color-mix(in srgb, #FF8A3D 75%, #1D1915)",
              "--dsw-static-blue-400": "color-mix(in srgb, #FF8A3D 85%, #1D1915)",
              "--dsw-static-blue-450": "#FF8A3D",
              "--dsw-static-blue-500": "#FF8A3D",
              "--dsw-static-blue-600": "color-mix(in srgb, #FF8A3D 70%, #1D1915)",
              "--dsw-static-blue-800": "color-mix(in srgb, #FF8A3D 50%, #1D1915)",
              "--dsw-static-blue-900": "color-mix(in srgb, #FF8A3D 35%, #1D1915)",
              "--dsw-static-blue-950": "color-mix(in srgb, #FF8A3D 25%, #1D1915)",
              "--dsw-static-blue-50p": "color-mix(in srgb, #FF8A3D 45%, #EDE6DA)",
              "--dsw-static-green-100": "color-mix(in srgb, #8FC97F 30%, #EDE6DA)",
              "--dsw-static-green-400": "color-mix(in srgb, #8FC97F 75%, #1D1915)",
              "--dsw-static-green-500": "#8FC97F",
              "--dsw-static-green-900": "color-mix(in srgb, #8FC97F 35%, #1D1915)",
              "--dsw-static-red-50": "color-mix(in srgb, #FF5A5F 40%, #EDE6DA)",
              "--dsw-static-red-100": "color-mix(in srgb, #FF5A5F 25%, #EDE6DA)",
              "--dsw-static-red-400": "color-mix(in srgb, #FF5A5F 75%, #1D1915)",
              "--dsw-static-red-500": "#FF5A5F",
              "--dsw-static-red-600": "color-mix(in srgb, #FF5A5F 65%, #1D1915)",
              "--dsw-static-red-900": "color-mix(in srgb, #FF5A5F 35%, #1D1915)",
              "--dsw-static-amber-100": "color-mix(in srgb, #FFC53D 30%, #EDE6DA)",
              "--dsw-static-amber-400": "color-mix(in srgb, #FFC53D 85%, #1D1915)",
              "--dsw-static-amber-500": "#FFB930",
              "--dsw-static-amber-600": "#FFB930",
              "--dsw-static-amber-900": "color-mix(in srgb, #FFB930 40%, #1D1915)",
              "--dsw-csm-orange": "#FF8A3D",
              "--dsw-csm-red": "#FF5A5F",
              "--dsw-csm-gold": "#FFB930",
              "--dsw-csm-cream": "#EDE6DA",
              "--dsw-pack-accent": "#FF8A3D",
              "--dsw-pack-accent-soft": "#FFB37A",
              "--dsw-alias-bg-base": "#1D1915",
              "--dsw-alias-bg-layer-1": "#16110E",
              "--dsw-alias-bg-layer-2": "#2A241E",
              "--dsw-alias-bg-layer-3": "#3A332B",
              "--dsw-alias-bg-overlay": "#2A241E",
              "--dsw-alias-bg-mask-1": "rgba(16, 12, 10, 0.5)",
              "--dsw-alias-bg-mask-2": "rgba(16, 12, 10, 0.2)",
              "--dsw-alias-bg-mask-3": "rgba(16, 12, 10, 0.48)",
              "--dsw-alias-bg-module-platform": "#2A241E",
              "--dsw-alias-bg-multi-select": "#2A241E",
              "--dsw-alias-bg-skeleton": "rgba(58, 51, 43, 0.08)",
              "--dsw-alias-border-l1": "rgba(131, 121, 107, 0.25)",
              "--dsw-alias-border-l2": "rgba(131, 121, 107, 0.45)",
              "--dsw-alias-border-l3": "rgba(131, 121, 107, 0.55)",
              "--dsw-alias-border-l4": "rgba(131, 121, 107, 0.7)",
              "--dsw-alias-label-primary": "#EDE6DA",
              "--dsw-alias-label-secondary": "#B5AB9C",
              "--dsw-alias-label-tertiary": "#CFC6B8",
              "--dsw-alias-label-caption": "#CFC6B8",
              "--dsw-alias-label-dimmed": "#CFC6B8",
              "--dsw-alias-brand-primary": "#FF8A3D",
              "--dsw-alias-brand-text": "#241108",
              "--dsw-alias-button-primary-hover": "#FFA15C",
              "--dsw-alias-button-primary-dimmed": "#2A241E",
              "--dsw-alias-button-elevated-fill": "#2A241E",
              "--dsw-alias-button-floating-fill": "#3A332B",
              "--dsw-alias-button-floating-hover": "#5B5348",
              "--dsw-alias-button-ghost-active-border": "#5B5348",
              "--dsw-alias-button-ghost-active-fill": "#2A241E",
              "--dsw-alias-button-ghost-active-hover": "#3A332B",
              "--dsw-alias-state-business-primary": "#FF8A3D",
              "--dsw-alias-state-business-tertiary": "#2A241E",
              "--dsw-alias-state-error-primary": "#FF5A5F",
              "--dsw-alias-state-error-secondary": "#FF5A5F",
              "--dsw-alias-state-success-primary": "#8FC97F",
              "--dsw-alias-state-success-secondary": "#8FC97F",
              "--dsw-alias-state-success-tertiary": "#2A241E",
              "--dsw-alias-state-warn-label": "#FFC53D",
              "--dsw-alias-state-warn-primary": "#FFB930",
              "--dsw-alias-state-warn-secondary": "#FFB930",
              "--dsw-alias-state-warn-tertiary": "#2A241E",
              "--dsw-alias-interactive-bg-hover": "rgba(42, 36, 30, 0.45)",
              "--dsw-alias-interactive-bg-active": "rgba(58, 51, 43, 0.55)",
              "--dsw-alias-interactive-bg-hover-accent": "rgba(255, 138, 61, 0.14)",
              "--dsw-alias-interactive-bg-hover-danger": "rgba(255, 90, 95, 0.15)",
              "--dsw-alias-interactive-bg-hover-solid": "#3A332B",
              "--dsw-alias-markdown-code-block": "#16110E",
              "--dsw-alias-markdown-code-block-banner": "#2A241E",
              "--dsw-alias-markdown-code-segment-selected": "#2A241E",
              "--dsw-alias-markdown-code-segment-unselected": "#16110E",
              "--dsw-alias-markdown-citation": "#2A241E",
              "--dsw-alias-markdown-inline-code": "#2A241E",
              "--dsw-alias-markdown-placeholder": "#2A241E",
              "--dsw-alias-markdown-tag": "#2A241E",
              "--dsw-alias-toast-bg": "#16110E",
              "--dsw-alias-tooltip-bg": "#2A241E",
              "--dsw-alias-separator-primary": "rgba(255, 138, 61, 0.8)",
              "--dsw-alias-scrollbar-bg-l1": "#2A241E",
              "--dsw-alias-scrollbar-bg-l2": "#3A332B",
              "--dsw-alias-scrollbar-hover-l1": "#5B5348",
              "--dsw-alias-scrollbar-hover-l2": "#5B5348",
              "--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
              "--dsw-alias-bg-mask-drop": "rgba(29, 25, 21, 0.7)",
              "--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.06)",
              "--dsw-alias-border-inverted2": "rgba(255, 255, 255, 0.08)",
              "--dsw-alias-border-l2-darkmode-thin": "rgba(131, 121, 107, 0.3)",
              "--dsw-alias-brand-primary-invert": "#EDE6DA",
              "--dsw-alias-brand-primary-new-colorprimary-new-color": "#FF8A3D",
              "--dsw-alias-button-contrast-fill": "#EDE6DA",
              "--dsw-alias-button-info-fill": "#FF8A3D",
              "--dsw-alias-button-info-hover": "#8F4A1F",
              "--dsw-alias-button-primary-fill": "#FF8A3D",
              "--dsw-alias-button-tool-bar-fill": "rgba(131, 121, 107, 0.5)",
              "--dsw-alias-button-tool-bar-fill-invisible": "rgba(131, 121, 107, 0.36)",
              "--dsw-alias-button-tool-bar-hover": "rgba(155, 144, 129, 0.6)",
              "--dsw-alias-label-primary-bluish": "#EDE6DA",
              "--dsw-alias-label-primary-dimmed": "#B5AB9C",
              "--dsw-alias-label-primary-foreground": "#16110E",
              "--dsw-alias-label-primary-inverted": "#2A241E",
              "--dsw-specific-sidebar-fill": "#16110E",
              "--dsw-specific-sidebar-nav-item-active": "#3A332B",
              "--dsw-specific-sidebar-nav-item-active-accent": "rgba(255, 138, 61, 0.25)",
              "--dsw-specific-sidebar-nav-item-hover": "#2A241E",
              "--dsw-specific-bubble": "#2A241E",
              "--dsw-specific-bubble-highlight": "#3A332B",
              "--dsw-specific-input-major": "#16110E",
              "--dsw-specific-login-input": "#16110E",
              "--dsw-specific-menu": "#2A241E",
              "--dsw-specific-selector": "#3A332B",
              "--dsw-specific-tip": "#2A241E",
              "--shiki-foreground": "#EDE6DA",
              "--shiki-background": "#16110E",
              "--shiki-token-constant": "#FFB930",
              "--shiki-token-string": "#8FC97F",
              "--shiki-token-comment": "#83796B",
              "--shiki-token-keyword": "#FF8A3D",
              "--shiki-token-parameter": "#D9A06B",
              "--shiki-token-function": "#F0655A",
              "--shiki-token-string-expression": "#8FC97F",
              "--shiki-token-punctuation": "#9B9081",
              "--shiki-token-link": "#FFC53D"
            }
          }
        ]
      },
      {
        "id": "gundam",
        "names": {
          "zh": "高达",
          "en": "Gundam"
        },
        "skins": [
          {
            "id": "gundam-light",
            "name": "Gundam Light",
            "colorScheme": "light",
            "tokens": {
              "--dsw-static-neutral-bluish-50": "color-mix(in srgb, #EFEEE6 50%, #E3E2D6)",
              "--dsw-static-neutral-50": "color-mix(in srgb, #EFEEE6 50%, #E3E2D6)",
              "--dsw-static-neutral-bluish-60": "#E3E2D6",
              "--dsw-static-neutral-60": "#E3E2D6",
              "--dsw-static-neutral-bluish-75": "color-mix(in srgb, #E3E2D6 50%, #CDCDBE)",
              "--dsw-static-neutral-75": "color-mix(in srgb, #E3E2D6 50%, #CDCDBE)",
              "--dsw-static-neutral-bluish-100": "#CDCDBE",
              "--dsw-static-neutral-100": "#CDCDBE",
              "--dsw-static-neutral-bluish-150": "color-mix(in srgb, #CDCDBE 50%, #BCBDAD)",
              "--dsw-static-neutral-150": "color-mix(in srgb, #CDCDBE 50%, #BCBDAD)",
              "--dsw-static-neutral-bluish-200": "#BCBDAD",
              "--dsw-static-neutral-200": "#BCBDAD",
              "--dsw-static-neutral-bluish-250": "color-mix(in srgb, #BCBDAD 50%, #A7A999)",
              "--dsw-static-neutral-250": "color-mix(in srgb, #BCBDAD 50%, #A7A999)",
              "--dsw-static-neutral-bluish-300": "#A7A999",
              "--dsw-static-neutral-300": "#A7A999",
              "--dsw-static-neutral-bluish-400": "color-mix(in srgb, #A7A999 50%, #7E8694)",
              "--dsw-static-neutral-400": "color-mix(in srgb, #A7A999 50%, #7E8694)",
              "--dsw-static-neutral-bluish-500": "#7E8694",
              "--dsw-static-neutral-500": "#7E8694",
              "--dsw-static-neutral-bluish-550": "color-mix(in srgb, #7E8694 50%, #6E7686)",
              "--dsw-static-neutral-550": "color-mix(in srgb, #7E8694 50%, #6E7686)",
              "--dsw-static-neutral-bluish-600": "#6E7686",
              "--dsw-static-neutral-600": "#6E7686",
              "--dsw-static-neutral-bluish-700": "color-mix(in srgb, #6E7686 50%, #5B6375)",
              "--dsw-static-neutral-700": "color-mix(in srgb, #6E7686 50%, #5B6375)",
              "--dsw-static-neutral-bluish-750": "#5B6375",
              "--dsw-static-neutral-750": "#5B6375",
              "--dsw-static-neutral-bluish-800": "color-mix(in srgb, #5B6375 50%, #4A5166)",
              "--dsw-static-neutral-800": "color-mix(in srgb, #5B6375 50%, #4A5166)",
              "--dsw-static-neutral-bluish-850": "#4A5166",
              "--dsw-static-neutral-850": "#4A5166",
              "--dsw-static-neutral-bluish-875": "color-mix(in srgb, #4A5166 50%, #363D52)",
              "--dsw-static-neutral-875": "color-mix(in srgb, #4A5166 50%, #363D52)",
              "--dsw-static-neutral-bluish-900": "#363D52",
              "--dsw-static-neutral-900": "#363D52",
              "--dsw-static-neutral-bluish-950": "color-mix(in srgb, #363D52 50%, #2A3045)",
              "--dsw-static-neutral-950": "color-mix(in srgb, #363D52 50%, #2A3045)",
              "--dsw-static-neutral-bluish-1000": "#2A3045",
              "--dsw-static-neutral-1000": "#2A3045",
              "--dsw-static-neutral-bluish-00": "#EFEEE6",
              "--dsw-static-neutral-00": "#EFEEE6",
              "--dsw-static-deepseek-50": "color-mix(in srgb, #1E3A8F 60%, #EFEEE6)",
              "--dsw-static-deepseek-100": "color-mix(in srgb, #1E3A8F 40%, #EFEEE6)",
              "--dsw-static-deepseek-200": "#5470C9",
              "--dsw-static-deepseek-300": "color-mix(in srgb, #1E3A8F 75%, #EFEEE6)",
              "--dsw-static-deepseek-400": "#1E3A8F",
              "--dsw-static-deepseek-450": "#1E3A8F",
              "--dsw-static-deepseek-500": "#1E3A8F",
              "--dsw-static-deepseek-600": "color-mix(in srgb, #1E3A8F 65%, #363D52)",
              "--dsw-static-deepseek-800": "color-mix(in srgb, #1E3A8F 30%, #363D52)",
              "--dsw-static-deepseek-900": "color-mix(in srgb, #1E3A8F 18%, #363D52)",
              "--dsw-static-deepseek-700-delete": "color-mix(in srgb, #1E3A8F 45%, #363D52)",
              "--dsw-static-blue-50": "color-mix(in srgb, #2E5AAC 55%, #EFEEE6)",
              "--dsw-static-blue-75": "color-mix(in srgb, #2E5AAC 35%, #EFEEE6)",
              "--dsw-static-blue-100": "color-mix(in srgb, #2E5AAC 28%, #EFEEE6)",
              "--dsw-static-blue-300": "color-mix(in srgb, #2E5AAC 78%, #EFEEE6)",
              "--dsw-static-blue-400": "color-mix(in srgb, #2E5AAC 88%, #EFEEE6)",
              "--dsw-static-blue-450": "#1E3A8F",
              "--dsw-static-blue-500": "#1E3A8F",
              "--dsw-static-blue-600": "color-mix(in srgb, #2E5AAC 70%, #363D52)",
              "--dsw-static-blue-800": "color-mix(in srgb, #2E5AAC 50%, #363D52)",
              "--dsw-static-blue-900": "color-mix(in srgb, #2E5AAC 35%, #363D52)",
              "--dsw-static-blue-950": "color-mix(in srgb, #2E5AAC 25%, #363D52)",
              "--dsw-static-blue-50p": "color-mix(in srgb, #2E5AAC 48%, #EFEEE6)",
              "--dsw-static-green-100": "color-mix(in srgb, #3D7A44 35%, #EFEEE6)",
              "--dsw-static-green-400": "color-mix(in srgb, #3D7A44 80%, #EFEEE6)",
              "--dsw-static-green-500": "#3D7A44",
              "--dsw-static-green-900": "color-mix(in srgb, #3D7A44 35%, #363D52)",
              "--dsw-static-red-50": "color-mix(in srgb, #C8102E 45%, #EFEEE6)",
              "--dsw-static-red-100": "color-mix(in srgb, #C8102E 28%, #EFEEE6)",
              "--dsw-static-red-400": "color-mix(in srgb, #C8102E 78%, #EFEEE6)",
              "--dsw-static-red-500": "#C8102E",
              "--dsw-static-red-600": "color-mix(in srgb, #C8102E 68%, #363D52)",
              "--dsw-static-red-900": "color-mix(in srgb, #C8102E 35%, #363D52)",
              "--dsw-static-amber-100": "color-mix(in srgb, #D9A00F 35%, #EFEEE6)",
              "--dsw-static-amber-400": "color-mix(in srgb, #D9A00F 88%, #EFEEE6)",
              "--dsw-static-amber-500": "#C98A04",
              "--dsw-static-amber-600": "#C98A04",
              "--dsw-static-amber-900": "color-mix(in srgb, #C98A04 40%, #363D52)",
              "--dsw-gnd-blue": "#1E3A8F",
              "--dsw-gnd-red": "#C8102E",
              "--dsw-gnd-yellow": "#D9A00F",
              "--dsw-gnd-white": "#EFEEE6",
              "--dsw-pack-accent": "#1E3A8F",
              "--dsw-pack-accent-soft": "#5470C9",
              "--dsw-alias-bg-base": "#EFEEE6",
              "--dsw-alias-bg-layer-1": "#EFEEE6",
              "--dsw-alias-bg-layer-2": "#E3E2D6",
              "--dsw-alias-bg-layer-3": "#CDCDBE",
              "--dsw-alias-bg-overlay": "#EFEEE6",
              "--dsw-alias-bg-mask-1": "rgba(210, 210, 198, 0.24)",
              "--dsw-alias-bg-mask-2": "rgba(210, 210, 198, 0.12)",
              "--dsw-alias-bg-mask-3": "rgba(210, 210, 198, 0.48)",
              "--dsw-alias-bg-module-platform": "#E3E2D6",
              "--dsw-alias-bg-multi-select": "#E3E2D6",
              "--dsw-alias-bg-skeleton": "rgba(74, 81, 102, 0.08)",
              "--dsw-alias-border-l1": "rgba(90, 98, 120, 0.28)",
              "--dsw-alias-border-l2": "rgba(90, 98, 120, 0.45)",
              "--dsw-alias-border-l3": "rgba(90, 98, 120, 0.58)",
              "--dsw-alias-border-l4": "rgba(90, 98, 120, 0.72)",
              "--dsw-alias-label-primary": "#363D52",
              "--dsw-alias-label-secondary": "#5B6375",
              "--dsw-alias-label-tertiary": "#4A5166",
              "--dsw-alias-label-caption": "#4A5166",
              "--dsw-alias-label-dimmed": "#4A5166",
              "--dsw-alias-brand-primary": "#1E3A8F",
              "--dsw-alias-brand-text": "#F2F4FB",
              "--dsw-alias-button-primary-hover": "#2A4FB8",
              "--dsw-alias-button-primary-dimmed": "#E3E2D6",
              "--dsw-alias-button-elevated-fill": "#EFEEE6",
              "--dsw-alias-button-floating-fill": "#EFEEE6",
              "--dsw-alias-button-floating-hover": "#E3E2D6",
              "--dsw-alias-button-ghost-active-border": "#BCBDAD",
              "--dsw-alias-button-ghost-active-fill": "#E3E2D6",
              "--dsw-alias-button-ghost-active-hover": "#CDCDBE",
              "--dsw-alias-state-business-primary": "#1E3A8F",
              "--dsw-alias-state-business-tertiary": "#E3E2D6",
              "--dsw-alias-state-error-primary": "#C8102E",
              "--dsw-alias-state-error-secondary": "#C8102E",
              "--dsw-alias-state-success-primary": "#3D7A44",
              "--dsw-alias-state-success-secondary": "#3D7A44",
              "--dsw-alias-state-success-tertiary": "#E3E2D6",
              "--dsw-alias-state-warn-label": "#8A6500",
              "--dsw-alias-state-warn-primary": "#B7860B",
              "--dsw-alias-state-warn-secondary": "#B7860B",
              "--dsw-alias-state-warn-tertiary": "#E3E2D6",
              "--dsw-alias-interactive-bg-hover": "rgba(74, 81, 102, 0.10)",
              "--dsw-alias-interactive-bg-active": "rgba(74, 81, 102, 0.16)",
              "--dsw-alias-interactive-bg-hover-accent": "rgba(30, 58, 143, 0.10)",
              "--dsw-alias-interactive-bg-hover-danger": "rgba(200, 16, 46, 0.06)",
              "--dsw-alias-interactive-bg-hover-solid": "#E3E2D6",
              "--dsw-alias-markdown-code-block": "#E3E2D6",
              "--dsw-alias-markdown-code-block-banner": "#E3E2D6",
              "--dsw-alias-markdown-code-segment-selected": "#EFEEE6",
              "--dsw-alias-markdown-code-segment-unselected": "#E3E2D6",
              "--dsw-alias-markdown-citation": "#E3E2D6",
              "--dsw-alias-markdown-inline-code": "#E3E2D6",
              "--dsw-alias-markdown-placeholder": "#E3E2D6",
              "--dsw-alias-markdown-tag": "#E3E2D6",
              "--dsw-alias-toast-bg": "#CDCDBE",
              "--dsw-alias-tooltip-bg": "#BCBDAD",
              "--dsw-alias-separator-primary": "rgba(30, 58, 143, 0.7)",
              "--dsw-alias-scrollbar-bg-l1": "#CDCDBE",
              "--dsw-alias-scrollbar-bg-l2": "#BCBDAD",
              "--dsw-alias-scrollbar-hover-l1": "#A7A999",
              "--dsw-alias-scrollbar-hover-l2": "#A7A999",
              "--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
              "--dsw-alias-bg-mask-drop": "rgba(255, 255, 255, 0.7)",
              "--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
              "--dsw-alias-border-inverted2": "rgba(0, 0, 0, 0)",
              "--dsw-alias-border-l2-darkmode-thin": "rgba(90, 98, 120, 0.35)",
              "--dsw-alias-brand-primary-invert": "#363D52",
              "--dsw-alias-brand-primary-new-colorprimary-new-color": "#1E3A8F",
              "--dsw-alias-button-contrast-fill": "#363D52",
              "--dsw-alias-button-info-fill": "#1E3A8F",
              "--dsw-alias-button-info-hover": "#6C84D6",
              "--dsw-alias-button-primary-fill": "#1E3A8F",
              "--dsw-alias-button-tool-bar-fill": "rgba(90, 98, 120, 0.5)",
              "--dsw-alias-button-tool-bar-fill-invisible": "rgba(90, 98, 120, 0.36)",
              "--dsw-alias-button-tool-bar-hover": "rgba(110, 118, 134, 0.6)",
              "--dsw-alias-label-primary-bluish": "#363D52",
              "--dsw-alias-label-primary-dimmed": "#5B6375",
              "--dsw-alias-label-primary-foreground": "#EFEEE6",
              "--dsw-alias-label-primary-inverted": "#EFEEE6",
              "--dsw-specific-sidebar-fill": "#E3E2D6",
              "--dsw-specific-sidebar-nav-item-active": "#BCBDAD",
              "--dsw-specific-sidebar-nav-item-active-accent": "rgba(30, 58, 143, 0.2)",
              "--dsw-specific-sidebar-nav-item-hover": "#CDCDBE",
              "--dsw-specific-bubble": "#E3E2D6",
              "--dsw-specific-bubble-highlight": "#CDCDBE",
              "--dsw-specific-input-major": "#EFEEE6",
              "--dsw-specific-login-input": "#E3E2D6",
              "--dsw-specific-menu": "#E3E2D6",
              "--dsw-specific-selector": "#CDCDBE",
              "--dsw-specific-tip": "#E3E2D6",
              "--shiki-foreground": "#363D52",
              "--shiki-background": "#E3E2D6",
              "--shiki-token-constant": "#B45F06",
              "--shiki-token-string": "#3D7A44",
              "--shiki-token-comment": "#7E8694",
              "--shiki-token-keyword": "#1E3A8F",
              "--shiki-token-parameter": "#C8102E",
              "--shiki-token-function": "#2E5AAC",
              "--shiki-token-string-expression": "#3D7A44",
              "--shiki-token-punctuation": "#5B6375",
              "--shiki-token-link": "#8A6500"
            }
          },
          {
            "id": "gundam-dark",
            "name": "Gundam Dark",
            "colorScheme": "dark",
            "tokens": {
              "--dsw-static-neutral-bluish-50": "color-mix(in srgb, #E4E6EF 50%, #C6CBDA)",
              "--dsw-static-neutral-50": "color-mix(in srgb, #E4E6EF 50%, #C6CBDA)",
              "--dsw-static-neutral-bluish-60": "#C6CBDA",
              "--dsw-static-neutral-60": "#C6CBDA",
              "--dsw-static-neutral-bluish-75": "color-mix(in srgb, #C6CBDA 50%, #AEB4C7)",
              "--dsw-static-neutral-75": "color-mix(in srgb, #C6CBDA 50%, #AEB4C7)",
              "--dsw-static-neutral-bluish-100": "#AEB4C7",
              "--dsw-static-neutral-100": "#AEB4C7",
              "--dsw-static-neutral-bluish-150": "color-mix(in srgb, #AEB4C7 50%, #969DB3)",
              "--dsw-static-neutral-150": "color-mix(in srgb, #AEB4C7 50%, #969DB3)",
              "--dsw-static-neutral-bluish-200": "#969DB3",
              "--dsw-static-neutral-200": "#969DB3",
              "--dsw-static-neutral-bluish-250": "color-mix(in srgb, #969DB3 50%, #7F87A0)",
              "--dsw-static-neutral-250": "color-mix(in srgb, #969DB3 50%, #7F87A0)",
              "--dsw-static-neutral-bluish-300": "#7F87A0",
              "--dsw-static-neutral-300": "#7F87A0",
              "--dsw-static-neutral-bluish-400": "color-mix(in srgb, #7F87A0 50%, #565E78)",
              "--dsw-static-neutral-400": "color-mix(in srgb, #7F87A0 50%, #565E78)",
              "--dsw-static-neutral-bluish-500": "#565E78",
              "--dsw-static-neutral-500": "#565E78",
              "--dsw-static-neutral-bluish-550": "color-mix(in srgb, #565E78 50%, #3A415A)",
              "--dsw-static-neutral-550": "color-mix(in srgb, #565E78 50%, #3A415A)",
              "--dsw-static-neutral-bluish-600": "#3A415A",
              "--dsw-static-neutral-600": "#3A415A",
              "--dsw-static-neutral-bluish-700": "color-mix(in srgb, #3A415A 50%, #2A3044)",
              "--dsw-static-neutral-700": "color-mix(in srgb, #3A415A 50%, #2A3044)",
              "--dsw-static-neutral-bluish-750": "#2A3044",
              "--dsw-static-neutral-750": "#2A3044",
              "--dsw-static-neutral-bluish-800": "color-mix(in srgb, #2A3044 50%, #171A26)",
              "--dsw-static-neutral-800": "color-mix(in srgb, #2A3044 50%, #171A26)",
              "--dsw-static-neutral-bluish-850": "#171A26",
              "--dsw-static-neutral-850": "#171A26",
              "--dsw-static-neutral-bluish-875": "color-mix(in srgb, #171A26 50%, #12141C)",
              "--dsw-static-neutral-875": "color-mix(in srgb, #171A26 50%, #12141C)",
              "--dsw-static-neutral-bluish-900": "#12141C",
              "--dsw-static-neutral-900": "#12141C",
              "--dsw-static-neutral-bluish-950": "color-mix(in srgb, #12141C 50%, #0C0E16)",
              "--dsw-static-neutral-950": "color-mix(in srgb, #12141C 50%, #0C0E16)",
              "--dsw-static-neutral-bluish-1000": "#0C0E16",
              "--dsw-static-neutral-1000": "#0C0E16",
              "--dsw-static-neutral-bluish-00": "#E4E6EF",
              "--dsw-static-neutral-00": "#E4E6EF",
              "--dsw-static-deepseek-50": "color-mix(in srgb, #5B8CFF 55%, #E4E6EF)",
              "--dsw-static-deepseek-100": "color-mix(in srgb, #5B8CFF 35%, #E4E6EF)",
              "--dsw-static-deepseek-200": "#8FB0FF",
              "--dsw-static-deepseek-300": "color-mix(in srgb, #5B8CFF 70%, #171A26)",
              "--dsw-static-deepseek-400": "#5B8CFF",
              "--dsw-static-deepseek-450": "#5B8CFF",
              "--dsw-static-deepseek-500": "#5B8CFF",
              "--dsw-static-deepseek-600": "color-mix(in srgb, #5B8CFF 60%, #171A26)",
              "--dsw-static-deepseek-800": "color-mix(in srgb, #5B8CFF 30%, #171A26)",
              "--dsw-static-deepseek-900": "color-mix(in srgb, #5B8CFF 20%, #171A26)",
              "--dsw-static-deepseek-700-delete": "color-mix(in srgb, #5B8CFF 45%, #171A26)",
              "--dsw-static-blue-50": "color-mix(in srgb, #5B8CFF 55%, #E4E6EF)",
              "--dsw-static-blue-75": "color-mix(in srgb, #5B8CFF 35%, #E4E6EF)",
              "--dsw-static-blue-100": "color-mix(in srgb, #5B8CFF 25%, #E4E6EF)",
              "--dsw-static-blue-300": "color-mix(in srgb, #5B8CFF 75%, #171A26)",
              "--dsw-static-blue-400": "color-mix(in srgb, #5B8CFF 85%, #171A26)",
              "--dsw-static-blue-450": "#5B8CFF",
              "--dsw-static-blue-500": "#5B8CFF",
              "--dsw-static-blue-600": "color-mix(in srgb, #5B8CFF 70%, #171A26)",
              "--dsw-static-blue-800": "color-mix(in srgb, #5B8CFF 50%, #171A26)",
              "--dsw-static-blue-900": "color-mix(in srgb, #5B8CFF 35%, #171A26)",
              "--dsw-static-blue-950": "color-mix(in srgb, #5B8CFF 25%, #171A26)",
              "--dsw-static-blue-50p": "color-mix(in srgb, #5B8CFF 45%, #E4E6EF)",
              "--dsw-static-green-100": "color-mix(in srgb, #7BC96F 30%, #E4E6EF)",
              "--dsw-static-green-400": "color-mix(in srgb, #7BC96F 75%, #171A26)",
              "--dsw-static-green-500": "#7BC96F",
              "--dsw-static-green-900": "color-mix(in srgb, #7BC96F 35%, #171A26)",
              "--dsw-static-red-50": "color-mix(in srgb, #FF4D5E 40%, #E4E6EF)",
              "--dsw-static-red-100": "color-mix(in srgb, #FF4D5E 25%, #E4E6EF)",
              "--dsw-static-red-400": "color-mix(in srgb, #FF4D5E 75%, #171A26)",
              "--dsw-static-red-500": "#FF4D5E",
              "--dsw-static-red-600": "color-mix(in srgb, #FF4D5E 65%, #171A26)",
              "--dsw-static-red-900": "color-mix(in srgb, #FF4D5E 35%, #171A26)",
              "--dsw-static-amber-100": "color-mix(in srgb, #FFD766 30%, #E4E6EF)",
              "--dsw-static-amber-400": "color-mix(in srgb, #FFD766 85%, #171A26)",
              "--dsw-static-amber-500": "#FFC72C",
              "--dsw-static-amber-600": "#FFC72C",
              "--dsw-static-amber-900": "color-mix(in srgb, #FFC72C 40%, #171A26)",
              "--dsw-gnd-blue": "#5B8CFF",
              "--dsw-gnd-red": "#FF4D5E",
              "--dsw-gnd-yellow": "#FFC72C",
              "--dsw-gnd-white": "#E4E6EF",
              "--dsw-pack-accent": "#5B8CFF",
              "--dsw-pack-accent-soft": "#8FB0FF",
              "--dsw-alias-bg-base": "#171A26",
              "--dsw-alias-bg-layer-1": "#12141C",
              "--dsw-alias-bg-layer-2": "#2E3549",
              "--dsw-alias-bg-layer-3": "#3A415A",
              "--dsw-alias-bg-overlay": "#2E3549",
              "--dsw-alias-bg-mask-1": "rgba(12, 14, 22, 0.5)",
              "--dsw-alias-bg-mask-2": "rgba(12, 14, 22, 0.2)",
              "--dsw-alias-bg-mask-3": "rgba(12, 14, 22, 0.48)",
              "--dsw-alias-bg-module-platform": "#2E3549",
              "--dsw-alias-bg-multi-select": "#2E3549",
              "--dsw-alias-bg-skeleton": "rgba(58, 65, 90, 0.08)",
              "--dsw-alias-border-l1": "rgba(127, 135, 160, 0.25)",
              "--dsw-alias-border-l2": "rgba(127, 135, 160, 0.45)",
              "--dsw-alias-border-l3": "rgba(127, 135, 160, 0.55)",
              "--dsw-alias-border-l4": "rgba(127, 135, 160, 0.7)",
              "--dsw-alias-label-primary": "#E4E6EF",
              "--dsw-alias-label-secondary": "#AEB4C7",
              "--dsw-alias-label-tertiary": "#C6CBDA",
              "--dsw-alias-label-caption": "#C6CBDA",
              "--dsw-alias-label-dimmed": "#C6CBDA",
              "--dsw-alias-brand-primary": "#5B8CFF",
              "--dsw-alias-brand-text": "#0E1526",
              "--dsw-alias-button-primary-hover": "#7AA5FF",
              "--dsw-alias-button-primary-dimmed": "#2E3549",
              "--dsw-alias-button-elevated-fill": "#2E3549",
              "--dsw-alias-button-floating-fill": "#3A415A",
              "--dsw-alias-button-floating-hover": "#565E78",
              "--dsw-alias-button-ghost-active-border": "#565E78",
              "--dsw-alias-button-ghost-active-fill": "#2E3549",
              "--dsw-alias-button-ghost-active-hover": "#3A415A",
              "--dsw-alias-state-business-primary": "#5B8CFF",
              "--dsw-alias-state-business-tertiary": "#2E3549",
              "--dsw-alias-state-error-primary": "#FF4D5E",
              "--dsw-alias-state-error-secondary": "#FF4D5E",
              "--dsw-alias-state-success-primary": "#7BC96F",
              "--dsw-alias-state-success-secondary": "#7BC96F",
              "--dsw-alias-state-success-tertiary": "#2E3549",
              "--dsw-alias-state-warn-label": "#FFD766",
              "--dsw-alias-state-warn-primary": "#FFC72C",
              "--dsw-alias-state-warn-secondary": "#FFC72C",
              "--dsw-alias-state-warn-tertiary": "#2E3549",
              "--dsw-alias-interactive-bg-hover": "rgba(46, 53, 73, 0.45)",
              "--dsw-alias-interactive-bg-active": "rgba(58, 65, 90, 0.55)",
              "--dsw-alias-interactive-bg-hover-accent": "rgba(91, 140, 255, 0.14)",
              "--dsw-alias-interactive-bg-hover-danger": "rgba(255, 77, 94, 0.15)",
              "--dsw-alias-interactive-bg-hover-solid": "#3A415A",
              "--dsw-alias-markdown-code-block": "#12141C",
              "--dsw-alias-markdown-code-block-banner": "#2E3549",
              "--dsw-alias-markdown-code-segment-selected": "#2E3549",
              "--dsw-alias-markdown-code-segment-unselected": "#12141C",
              "--dsw-alias-markdown-citation": "#2E3549",
              "--dsw-alias-markdown-inline-code": "#2E3549",
              "--dsw-alias-markdown-placeholder": "#2E3549",
              "--dsw-alias-markdown-tag": "#2E3549",
              "--dsw-alias-toast-bg": "#12141C",
              "--dsw-alias-tooltip-bg": "#2E3549",
              "--dsw-alias-separator-primary": "rgba(91, 140, 255, 0.8)",
              "--dsw-alias-scrollbar-bg-l1": "#2E3549",
              "--dsw-alias-scrollbar-bg-l2": "#3A415A",
              "--dsw-alias-scrollbar-hover-l1": "#565E78",
              "--dsw-alias-scrollbar-hover-l2": "#565E78",
              "--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
              "--dsw-alias-bg-mask-drop": "rgba(23, 26, 38, 0.7)",
              "--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.06)",
              "--dsw-alias-border-inverted2": "rgba(255, 255, 255, 0.08)",
              "--dsw-alias-border-l2-darkmode-thin": "rgba(127, 135, 160, 0.3)",
              "--dsw-alias-brand-primary-invert": "#E4E6EF",
              "--dsw-alias-brand-primary-new-colorprimary-new-color": "#5B8CFF",
              "--dsw-alias-button-contrast-fill": "#E4E6EF",
              "--dsw-alias-button-info-fill": "#5B8CFF",
              "--dsw-alias-button-info-hover": "#33509E",
              "--dsw-alias-button-primary-fill": "#5B8CFF",
              "--dsw-alias-button-tool-bar-fill": "rgba(127, 135, 160, 0.5)",
              "--dsw-alias-button-tool-bar-fill-invisible": "rgba(127, 135, 160, 0.36)",
              "--dsw-alias-button-tool-bar-hover": "rgba(150, 157, 179, 0.6)",
              "--dsw-alias-label-primary-bluish": "#E4E6EF",
              "--dsw-alias-label-primary-dimmed": "#AEB4C7",
              "--dsw-alias-label-primary-foreground": "#12141C",
              "--dsw-alias-label-primary-inverted": "#2E3549",
              "--dsw-specific-sidebar-fill": "#12141C",
              "--dsw-specific-sidebar-nav-item-active": "#3A415A",
              "--dsw-specific-sidebar-nav-item-active-accent": "rgba(91, 140, 255, 0.25)",
              "--dsw-specific-sidebar-nav-item-hover": "#2E3549",
              "--dsw-specific-bubble": "#2E3549",
              "--dsw-specific-bubble-highlight": "#3A415A",
              "--dsw-specific-input-major": "#12141C",
              "--dsw-specific-login-input": "#12141C",
              "--dsw-specific-menu": "#2E3549",
              "--dsw-specific-selector": "#3A415A",
              "--dsw-specific-tip": "#2E3549",
              "--shiki-foreground": "#E4E6EF",
              "--shiki-background": "#12141C",
              "--shiki-token-constant": "#FFC72C",
              "--shiki-token-string": "#8FD07F",
              "--shiki-token-comment": "#7F87A0",
              "--shiki-token-keyword": "#7AA5FF",
              "--shiki-token-parameter": "#FF8A94",
              "--shiki-token-function": "#6FB7FF",
              "--shiki-token-string-expression": "#8FD07F",
              "--shiki-token-punctuation": "#969DB3",
              "--shiki-token-link": "#FFD766"
            }
          }
        ]
      }
    ];

    /** All skins of all families, flat — what gets registered. */
    const SKINS = CATALOG.flatMap((family) => family.skins);

    /**
     * Parse a runtime preference into { family, colorScheme } if it names
     * one of this pack's skins, else null.
     */
    function parseSkin(preference) {
      for (const family of CATALOG) {
        if (preference === `${family.id}-light`) return { family: family.id, colorScheme: "light" };
        if (preference === `${family.id}-dark`) return { family: family.id, colorScheme: "dark" };
      }
      return null;
    }

    /** Simplified Chinese dictionary (the key-set source of truth). */
    const zh = {
      "theme.title": "主题",
      "theme.default": "默认",
      "mode.light": "浅色",
      "mode.dark": "深色",
      "mode.system": "跟随系统"
    };

    /** English dictionary, checked complete against the zh key set. */
    const en = {
      "theme.title": "Themes",
      "theme.default": "Default",
      "mode.light": "Light",
      "mode.dark": "Dark",
      "mode.system": "System"
    };

    // Family display names come from the catalog data, not from code.
    for (const family of CATALOG) {
      zh[`family.${family.id}`] = family.names.zh;
      en[`family.${family.id}`] = family.names.en;
    }
    //#endregion

    //#region dsh-themes: meta preference (family × mode, with system follow)
    /** The OS color scheme, watched so "system" mode can follow it. */
    const darkQuery = window.matchMedia("(prefers-color-scheme: dark)");

    /**
     * The runtime preference is a single skin id — it has no notion of
     * "this family, follow the OS". The pack therefore persists a meta
     * preference `{family, mode}` and translates it into a concrete skin
     * id whenever it is applied: mode "system" resolves against the
     * current OS scheme, and the translation is re-run on every scheme
     * flip (see the darkQuery listener in apply).
     */
    function resolveSkin(pref) {
      if (!pref) return null;
      const mode = pref.mode === "system" ? (darkQuery.matches ? "dark" : "light") : pref.mode;
      return `${pref.family}-${mode}`;
    }

    /** Read the stored meta preference (null on absence/garbage/unknown). */
    function readPref() {
      try {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (typeof raw !== "string") return null;
        const parsed = JSON.parse(raw);
        if (
          parsed &&
          typeof parsed.family === "string" &&
          MODES.includes(parsed.mode) &&
          CATALOG.some((family) => family.id === parsed.family)
        ) {
          return { family: parsed.family, mode: parsed.mode };
        }
        return null;
      } catch {
        return null;
      }
    }

    /** Persist a meta preference; null clears the stored value. */
    function writePref(pref) {
      try {
        if (pref === null) window.localStorage.removeItem(STORAGE_KEY);
        else window.localStorage.setItem(STORAGE_KEY, JSON.stringify(pref));
      } catch {
        // storage unavailable / quota — the preference stays process-local
      }
    }
    //#endregion

    //#region dsh-themes: settings row store
    /**
     * Settings-row slot store: `{family, mode}` as derived from the theme
     * service snapshot plus the stored meta preference. The plugin's
     * apply-world change listener is the only writer; the row component
     * reads via props.useStore.
     */
    function createPrefStore() {
      return (0, _runtime_client.defineStore)({
        init: () => ({
          family: null,
          mode: "system",
          revision: -1
        }),
        actions: {
          sync: (d, family, mode, revision) => {
            if (revision <= d.revision) return;
            d.family = family;
            d.mode = mode;
            d.revision = revision;
          }
        }
      });
    }
    //#endregion

    //#region dsh-themes: settings row
    /** Inline style sheet for the row (kept dependency-free). */
    const styles = {
      group: {
        borderBottom: "1px solid var(--dsw-alias-border-l2)",
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        padding: "16px 0"
      },
      title: {
        color: "var(--dsw-alias-label-primary)",
        fontSize: "14px",
        fontWeight: 400,
        lineHeight: "22px"
      },
      grid: {
        display: "flex",
        flexWrap: "wrap",
        gap: "10px"
      },
      card: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "6px",
        width: "96px",
        padding: "3px",
        borderRadius: "10px",
        // longhand on purpose: the shorthand leaves borderColor to
        // fall back to currentColor once React clears the selected
        // override, painting stale black/white boxes on deselect
        borderWidth: "2px",
        borderStyle: "solid",
        borderColor: "transparent",
        background: "transparent",
        cursor: "pointer",
        font: "inherit",
        boxSizing: "border-box"
      },
      cardSelected: {
        borderColor: "var(--dsw-alias-brand-primary)",
        background: "var(--dsw-alias-interactive-bg-hover)"
      },
      cardLabel: {
        color: "var(--dsw-alias-label-secondary)",
        fontSize: "12px",
        lineHeight: "16px",
        whiteSpace: "nowrap"
      },
      cardLabelSelected: {
        color: "var(--dsw-alias-label-primary)"
      },
      splitSwatch: {
        width: "100%",
        height: "52px",
        borderRadius: "8px",
        boxSizing: "border-box",
        display: "flex",
        overflow: "hidden",
        border: "1px solid var(--dsw-alias-border-l2)"
      },
      swatchHalf: {
        flex: 1,
        padding: "8px 6px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        gap: "6px"
      },
      swatchLine: {
        height: "6px",
        borderRadius: "3px"
      },
      chips: {
        display: "flex",
        flexWrap: "wrap",
        gap: "8px"
      },
      chip: {
        padding: "4px 12px",
        borderRadius: "999px",
        // longhand, same reason as the card border
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "var(--dsw-alias-border-l2)",
        background: "transparent",
        color: "var(--dsw-alias-label-secondary)",
        fontSize: "12px",
        lineHeight: "16px",
        cursor: "pointer",
        font: "inherit",
        boxSizing: "border-box"
      },
      chipSelected: {
        borderColor: "var(--dsw-alias-brand-primary)",
        color: "var(--dsw-alias-brand-primary)",
        background: "var(--dsw-alias-interactive-bg-hover-accent)"
      }
    };

    /** One half of a family swatch: the skin's ground with text + brand stripes. */
    function SwatchHalf({ tokens }) {
      return (0, react_jsx_runtime.jsxs)("div", {
        style: {
          ...styles.swatchHalf,
          background: tokens["--dsw-alias-bg-layer-1"]
        },
        children: [
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "75%",
              background: tokens["--dsw-alias-label-primary"],
              opacity: 0.85
            }
          }),
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "55%",
              background: tokens["--dsw-alias-brand-primary"]
            }
          })
        ]
      });
    }

    /** Family preview: light skin on the left half, dark on the right. */
    function FamilySwatch({ family }) {
      const light = family.skins.find((skin) => skin.colorScheme === "light");
      const dark = family.skins.find((skin) => skin.colorScheme === "dark");
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.splitSwatch,
        children: [
          (0, react_jsx_runtime.jsx)(SwatchHalf, { tokens: light.tokens }),
          (0, react_jsx_runtime.jsx)(SwatchHalf, { tokens: dark.tokens })
        ]
      });
    }

    /** "Default" chip: follow the built-in appearance (light + dark halves). */
    function DefaultSwatch() {
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.splitSwatch,
        children: [
          (0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#f4f4f5" } }),
          (0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#1c1c20" } })
        ]
      });
    }

    /** One selectable family card. */
    function FamilyCard({ family, selected, onSelect, t }) {
      return (0, react_jsx_runtime.jsxs)("button", {
        type: "button",
        onClick: (event) => {
          onSelect();
          // drop focus so a stale focus ring never outlives the selection
          event.currentTarget.blur();
        },
        "aria-pressed": selected,
        style: {
          ...styles.card,
          ...(selected ? styles.cardSelected : {})
        },
        children: [
          (0, react_jsx_runtime.jsx)(FamilySwatch, { family }),
          (0, react_jsx_runtime.jsx)("span", {
            style: {
              ...styles.cardLabel,
              ...(selected ? styles.cardLabelSelected : {})
            },
            children: t(`family.${family.id}`)
          })
        ]
      });
    }

    /** One mode chip (light / dark / system). */
    function ModeChip({ label, selected, onSelect }) {
      return (0, react_jsx_runtime.jsx)("button", {
        type: "button",
        onClick: (event) => {
          onSelect();
          event.currentTarget.blur();
        },
        "aria-pressed": selected,
        style: {
          ...styles.chip,
          ...(selected ? styles.chipSelected : {})
        },
        children: label
      });
    }

    /**
     * The pack's single settings row, registered into the Settings →
     * General item slot: a family card grid (Default + one per family)
     * and, once a family is chosen, the mode chips — light / dark /
     * follow-system.
     */
    function ThemeRow({ t, selectFamily, selectMode, useStore }) {
      const family = useStore((s) => s.family);
      const mode = useStore((s) => s.mode);
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.group,
        children: [
          (0, react_jsx_runtime.jsx)("div", {
            style: styles.title,
            children: t("theme.title")
          }),
          (0, react_jsx_runtime.jsxs)("div", {
            style: styles.grid,
            children: [
              (0, react_jsx_runtime.jsxs)("button", {
                type: "button",
                onClick: (event) => {
                  selectFamily(null);
                  event.currentTarget.blur();
                },
                "aria-pressed": family === null,
                style: {
                  ...styles.card,
                  ...(family === null ? styles.cardSelected : {})
                },
                children: [
                  (0, react_jsx_runtime.jsx)(DefaultSwatch, {}),
                  (0, react_jsx_runtime.jsx)("span", {
                    style: {
                      ...styles.cardLabel,
                      ...(family === null ? styles.cardLabelSelected : {})
                    },
                    children: t("theme.default")
                  })
                ]
              }),
              CATALOG.map((familyDefinition) => (0, react_jsx_runtime.jsx)(FamilyCard, {
                family: familyDefinition,
                selected: family === familyDefinition.id,
                onSelect: () => selectFamily(familyDefinition.id),
                t
              }, familyDefinition.id))
            ]
          }),
          family === null
            ? null
            : (0, react_jsx_runtime.jsx)("div", {
                style: styles.chips,
                children: MODES.map((modeId) => (0, react_jsx_runtime.jsx)(ModeChip, {
                  label: t(`mode.${modeId}`),
                  selected: mode === modeId,
                  onSelect: () => selectMode(modeId)
                }, modeId))
              })
        ]
      });
    }
    //#endregion

    //#region dsh-themes: client plugin body
    /**
     * Required services: theme runtime (skins, switching), slots/locale
     * (the settings row). Persistence is localStorage, so no settings
     * transport is needed.
     */
    const inject = [
      "slots",
      "locale",
      "theme"
    ];

    /**
     * Client plugin body: register every skin into the theme runtime,
     * restore the saved meta preference (translating "system" against the
     * OS scheme and following its flips), keep the row's store in sync
     * with theme/change, and register the picker into Settings → General.
     * @param ctx - client cordis context.
     */
    function apply(ctx) {
      const disposers = SKINS.map((skinDefinition) => ctx.theme.register(skinDefinition));
      ctx.effect(() => () => {
        for (const dispose of disposers) dispose();
      }, "dsh-themes: theme registration");

      // Minimal surface tint: the user-message bubble carries a brand wash
      // so the two roles read apart; assistant replies intentionally stay
      // on the bare canvas. Message reference chips follow the brand. The
      // rules reference --dsw-pack-accent, which every skin in the pack
      // defines, so they work unchanged for every family. Keyed on stable
      // CSS-module suffixes.
      //
      // Every selector is boosted with :not(#dsh-themes): the shipped ui-*
      // stylesheets are injected by React after ours, so a plain attribute
      // selector loses to the equally specific module class and the tint
      // silently dies. The :not(id) pseudo is a no-op predicate that only
      // raises specificity.
      //
      // The sheet is mounted only while one of the pack's skins is active
      // and removed on the "Default" preference, so the built-in
      // appearance stays pixel-identical unless the user picked a family.
      // Hashed class suffixes can shift between harness versions — keep
      // this list short on purpose.
      const boost = (selector) =>
        selector.split(",").map((part) => `${part.trim()}:not(#dsh-themes)`).join(",");
      const SURFACE_RULES = [
        // user bubble: brand wash over the layer-2 surface, stronger on
        // dark skins where the ground is deep
        [
          '[class$="_userStack"] [class$="_bubble"]',
          " background: color-mix(in srgb, var(--dsw-pack-accent) 30%, var(--dsw-alias-bg-layer-2));"
        ],
        // body[data-ds-dark-theme] is present on dark schemes only: light
        // skins tint at 16% so the pale wash stays quiet
        [
          'body:not([data-ds-dark-theme]) [class$="_userStack"] [class$="_bubble"]',
          " background: color-mix(in srgb, var(--dsw-pack-accent) 16%, var(--dsw-alias-bg-layer-2));"
        ],
        // message reference chips: recolor from the brand
        [
          '[class$="_refChip"]',
          " background: color-mix(in srgb, var(--dsw-alias-brand-primary) 22%, transparent);"
        ]
      ].map(([selector, body]) => `${boost(selector)} {\n${body}\n}`).join("\n");
      const style = document.createElement("style");
      style.textContent = SURFACE_RULES;
      const syncSurfaceTint = () => {
        const active = parseSkin(ctx.theme.getTheme().preference) !== null;
        if (active && !style.isConnected) document.head.appendChild(style);
        if (!active && style.isConnected) style.remove();
      };
      syncSurfaceTint();
      ctx.on("theme/change", syncSurfaceTint);
      ctx.effect(() => () => {
        style.remove();
      }, "dsh-themes: surface tint lifecycle");

      // Restore the saved meta preference. The ThemeService adopts its
      // durable built-in preference ("light"/"dark"/"system") from the
      // Host settings scope asynchronously after boot, which overwrites a
      // third-party preference restored too early. Re-assert the resolved
      // skin for a short boot window (a handful of change events or a few
      // seconds), then yield to subsequent user actions.
      let bootGuard = readPref() ? 3 : 0;
      const reassertSaved = () => {
        if (bootGuard <= 0) return;
        const target = resolveSkin(readPref());
        if (target === null) return;
        if (ctx.theme.getTheme().preference === target) return;
        bootGuard -= 1;
        ctx.theme.setTheme(target);
      };
      reassertSaved();
      const bootWindow = setTimeout(() => {
        bootGuard = 0;
      }, 5000);
      ctx.effect(() => () => {
        clearTimeout(bootWindow);
      }, "dsh-themes: boot restore window");

      // Follow the OS color scheme while the stored mode is "system":
      // re-translate the meta preference into a concrete skin on every
      // flip. Explicit light/dark modes are pinned and ignore this.
      const onSchemeChange = () => {
        const stored = readPref();
        if (stored && stored.mode === "system") {
          ctx.theme.setTheme(resolveSkin(stored));
        }
      };
      darkQuery.addEventListener("change", onSchemeChange);
      ctx.effect(() => () => {
        darkQuery.removeEventListener("change", onSchemeChange);
      }, "dsh-themes: color-scheme listener");

      const prefStore = createPrefStore();
      let storeBound;
      const syncStore = (snapshot) => {
        const parsed = parseSkin(snapshot.preference);
        const stored = readPref();
        const family = parsed ? parsed.family : null;
        const mode = parsed
          ? stored && stored.family === parsed.family
            ? stored.mode
            : parsed.colorScheme
          : "system";
        storeBound?.sync(family, mode, snapshot.revision);
      };
      ctx.on("theme/change", (snapshot) => {
        const preference = snapshot.preference;
        const stored = readPref();
        const parsed = parseSkin(preference);
        if (parsed && preference !== resolveSkin(stored)) {
          // One of the pack's skins became active without matching the
          // stored meta preference (picked through another entry point):
          // adopt it as an explicit light/dark choice.
          writePref({ family: parsed.family, mode: parsed.colorScheme });
        } else if (!parsed && preference !== "light" && preference !== "dark" && preference !== "system") {
          // Another plugin's third-party theme took over: drop our stored
          // preference so only the last-picked plugin restores at boot
          // (both plugins must implement this convention).
          writePref(null);
        }
        syncStore(snapshot);
        // Re-assert from a fresh task: a re-entrant setTheme inside the
        // dispatch is missed by other subscribers (ui-layout's
        // ThemePresenter), so the restored skin would never reach the DOM.
        setTimeout(() => {
          reassertSaved();
        }, 0);
      });

      ctx.effect(() => ctx.locale.register(SETTINGS_NS, {
        zh,
        en
      }), "dsh-themes: settings row dictionaries");

      const themeInjected = (actions) => {
        storeBound = actions;
        syncStore(ctx.theme.getTheme());
        return {
          selectFamily: (familyId) => {
            if (familyId === null) {
              // Default: hand appearance back to the built-in light/dark/
              // system handling, natively following the OS.
              writePref(null);
              ctx.theme.setTheme("system");
              return;
            }
            // A freshly picked family starts in follow-system mode.
            const stored = readPref();
            const pref = {
              family: familyId,
              mode: stored && stored.family === familyId ? stored.mode : "system"
            };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          },
          selectMode: (mode) => {
            const stored = readPref();
            if (!stored) return;
            const pref = { family: stored.family, mode };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          }
        };
      };
      ctx.slots.inject("settings.general.item", () => ctx.slots.register({
        name: "settings.general.item",
        id: "themes",
        order: 19,
        store: prefStore,
        locale: SETTINGS_NS,
        inject: themeInjected
      }, ThemeRow));
    }
    //#endregion

    exports.CATALOG = CATALOG;
    exports.SKINS = SKINS;
    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
