// dsh-themes — browser half (client plugin bundle). GENERATED FILE:
// run `node scripts/gen-themes.mjs` to regenerate from lib/client.tpl.js.
//
// Loaded by dsh-client-modules at /plugins/dsh-themes/client.js and
// executed through the vendored cordis Loader's lazy-CJS module table
// (window.__ModuleLoader__.load). The factory body is plain CJS with
// require() resolved against the shell's module table — the same shape the
// shipped ui-* packages' bundles emit.
//
// Structure modeled on zhijun-dai/Catppuccin-dsh-theme (MIT).
window.__ModuleLoader__.load({
  id: "dsh-themes",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    let react_jsx_runtime = require("react/jsx-runtime");
    let react = require("react");
    let _runtime_client = require("@deepseek-ai/dsh-client-runtime/client");

    //#region dsh-themes: definitions
    /** The settings row's locale namespace. */
    const SETTINGS_NS = "settings.themes";
    /** localStorage key holding the meta preference `{family, mode, style}`. */
    const STORAGE_KEY = "dsh-themes:pref";
    /** Selectable modes; "system" follows the OS color scheme. */
    const MODES = ["light", "dark", "system"];
    /**
     * Selectable styles: "minimal" is the restrained look (plain surfaces,
     * no imagery); "vivid" adds the family wallpaper and heavier accents.
     */
    const STYLES = ["minimal", "vivid"];

    /**
     * The theme pack catalog, generated by scripts/gen-themes.mjs from
     * families/*.mjs: `[{ id, names: { zh, en }, decor, skins: [...] }]`.
     * `decor` carries the vivid settings entry's data — pal images as
     * data URIs plus the family's character-voice phrases (zh/en). A
     * family ships the styles its `styles` field lists (default both, so
     * four skins: light/dark × minimal/vivid; the IP families ship vivid
     * only, the neutral families minimal only). Each skin is a
     * third-party theme for the built-in ThemeRuntime: an id
     * (`<family>-<mode>` or `<family>-<mode>-vivid`), the colorScheme
     * driving body[data-ds-dark-theme], and --dsw-* overrides applied as
     * inline custom properties by ui-layout's ThemePresenter. Family ids
     * must not contain "-light"/"-dark" suffixes themselves.
     */
    const CATALOG = __CATALOG__;

    /** All skins of all families, flat — what gets registered. */
    const SKINS = CATALOG.flatMap((family) => family.skins);

    /**
     * Parse a runtime preference into { family, colorScheme, style } if it
     * names one of this pack's skins, else null.
     */
    function parseSkin(preference) {
      for (const family of CATALOG) {
        for (const colorScheme of ["light", "dark"]) {
          if (preference === `${family.id}-${colorScheme}`) {
            return { family: family.id, colorScheme, style: "minimal" };
          }
          if (preference === `${family.id}-${colorScheme}-vivid`) {
            return { family: family.id, colorScheme, style: "vivid" };
          }
        }
      }
      return null;
    }

    /** The styles a family actually ships, derived from its skin ids. */
    function familyStyles(familyId) {
      const family = CATALOG.find((entry) => entry.id === familyId);
      if (!family) return [];
      return STYLES.filter((style) =>
        family.skins.some((skin) =>
          style === "vivid" ? skin.id.endsWith("-vivid") : !skin.id.endsWith("-vivid")
        )
      );
    }

    /** Simplified Chinese dictionary (the key-set source of truth). */
    const zh = {
      "theme.title": "主题",
      "theme.default": "默认",
      "mode.light": "浅色",
      "mode.dark": "深色",
      "mode.system": "跟随系统",
      "style.minimal": "简约",
      "style.vivid": "氛围"
    };

    /** English dictionary, checked complete against the zh key set. */
    const en = {
      "theme.title": "Themes",
      "theme.default": "Default",
      "mode.light": "Light",
      "mode.dark": "Dark",
      "mode.system": "System",
      "style.minimal": "Minimal",
      "style.vivid": "Vivid"
    };

    // Family display names come from the catalog data, not from code.
    for (const family of CATALOG) {
      zh[`family.${family.id}`] = family.names.zh;
      en[`family.${family.id}`] = family.names.en;
    }
    //#endregion

    //#region dsh-themes: meta preference (family × mode, with system follow)
    /** The OS color scheme, watched so "system" mode can follow it. */
    const darkQuery = window.matchMedia("(prefers-color-scheme: dark)");

    /**
     * The runtime preference is a single skin id — it has no notion of
     * "this family, follow the OS" or "minimal vs vivid". The pack
     * therefore persists a meta preference `{family, mode, style}` and
     * translates it into a concrete skin id whenever it is applied: mode
     * "system" resolves against the current OS scheme, and the translation
     * is re-run on every scheme flip (see the darkQuery listener in apply).
     */
    function resolveSkin(pref) {
      if (!pref) return null;
      const mode = pref.mode === "system" ? (darkQuery.matches ? "dark" : "light") : pref.mode;
      const wanted = `${pref.family}-${mode}${pref.style === "vivid" ? "-vivid" : ""}`;
      const family = CATALOG.find((entry) => entry.id === pref.family);
      if (!family) return null;
      if (family.skins.some((skin) => skin.id === wanted)) return wanted;
      // the stored style predates a family restructuring (e.g. the minimal
      // skins moving out into the standalone neutral families) — fall back
      // to a style the family actually ships
      const fallback = family.skins.find((skin) => skin.colorScheme === mode);
      return fallback ? fallback.id : null;
    }

    /** Read the stored meta preference (null on absence/garbage/unknown). */
    function readPref() {
      try {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (typeof raw !== "string") return null;
        const parsed = JSON.parse(raw);
        if (
          parsed &&
          typeof parsed.family === "string" &&
          MODES.includes(parsed.mode) &&
          CATALOG.some((family) => family.id === parsed.family)
        ) {
          // preferences written before the style dimension existed default
          // to the family's first shipped style; a style the family no
          // longer ships is coerced the same way
          const shipped = familyStyles(parsed.family);
          const style = shipped.includes(parsed.style) ? parsed.style : shipped[0];
          if (!style) return null;
          return { family: parsed.family, mode: parsed.mode, style };
        }
        return null;
      } catch {
        return null;
      }
    }

    /** Persist a meta preference; null clears the stored value. */
    function writePref(pref) {
      try {
        if (pref === null) window.localStorage.removeItem(STORAGE_KEY);
        else window.localStorage.setItem(STORAGE_KEY, JSON.stringify(pref));
      } catch {
        // storage unavailable / quota — the preference stays process-local
      }
    }
    //#endregion

    //#region dsh-themes: settings row store
    /**
     * Settings-row slot store: `{family, mode}` as derived from the theme
     * service snapshot plus the stored meta preference. The plugin's
     * apply-world change listener is the only writer; the row component
     * reads via props.useStore.
     */
    function createPrefStore() {
      return (0, _runtime_client.defineStore)({
        init: () => ({
          family: null,
          mode: "system",
          style: "minimal",
          revision: -1
        }),
        actions: {
          sync: (d, family, mode, style, revision) => {
            if (revision <= d.revision) return;
            d.family = family;
            d.mode = mode;
            d.style = style;
            d.revision = revision;
          }
        }
      });
    }
    //#endregion

    //#region dsh-themes: settings row
    /** Inline style sheet for the row (kept dependency-free). */
    const styles = {
      group: {
        borderBottom: "1px solid var(--dsw-alias-border-l2)",
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        padding: "16px 0"
      },
      title: {
        color: "var(--dsw-alias-label-primary)",
        fontSize: "14px",
        fontWeight: 400,
        lineHeight: "22px"
      },
      grid: {
        display: "flex",
        flexWrap: "wrap",
        gap: "10px"
      },
      card: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "6px",
        width: "96px",
        padding: "3px",
        borderRadius: "10px",
        // longhand on purpose: the shorthand leaves borderColor to
        // fall back to currentColor once React clears the selected
        // override, painting stale black/white boxes on deselect
        borderWidth: "2px",
        borderStyle: "solid",
        borderColor: "transparent",
        background: "transparent",
        cursor: "pointer",
        font: "inherit",
        boxSizing: "border-box"
      },
      cardSelected: {
        borderColor: "var(--dsw-alias-brand-primary)",
        background: "var(--dsw-alias-interactive-bg-hover)"
      },
      cardLabel: {
        color: "var(--dsw-alias-label-secondary)",
        fontSize: "12px",
        lineHeight: "16px",
        whiteSpace: "nowrap"
      },
      cardLabelSelected: {
        color: "var(--dsw-alias-label-primary)"
      },
      splitSwatch: {
        width: "100%",
        height: "52px",
        borderRadius: "8px",
        boxSizing: "border-box",
        display: "flex",
        overflow: "hidden",
        border: "1px solid var(--dsw-alias-border-l2)"
      },
      swatchHalf: {
        flex: 1,
        padding: "8px 6px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        gap: "6px"
      },
      swatchLine: {
        height: "6px",
        borderRadius: "3px"
      },
      chips: {
        display: "flex",
        flexWrap: "wrap",
        gap: "8px"
      },
      chip: {
        padding: "4px 12px",
        borderRadius: "999px",
        // longhand, same reason as the card border
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "var(--dsw-alias-border-l2)",
        background: "transparent",
        color: "var(--dsw-alias-label-secondary)",
        fontSize: "12px",
        lineHeight: "16px",
        cursor: "pointer",
        font: "inherit",
        boxSizing: "border-box"
      },
      chipSelected: {
        borderColor: "var(--dsw-alias-brand-primary)",
        color: "var(--dsw-alias-brand-primary)",
        background: "var(--dsw-alias-interactive-bg-hover-accent)"
      }
    };

    /**
     * One half of a family swatch: the skin's ground carrying the family's
     * three signature stripes — brand (focus), signature (second color),
     * warning — so the card previews the full palette, not just the brand.
     */
    function SwatchHalf({ tokens }) {
      return (0, react_jsx_runtime.jsxs)("div", {
        style: {
          ...styles.swatchHalf,
          background: tokens["--dsw-alias-bg-layer-1"]
        },
        children: [
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "75%",
              background: tokens["--dsw-alias-brand-primary"]
            }
          }),
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "55%",
              background: tokens["--dsw-pack-signature"]
            }
          }),
          (0, react_jsx_runtime.jsx)("div", {
            style: {
              ...styles.swatchLine,
              width: "40%",
              background: tokens["--dsw-alias-state-warn-primary"]
            }
          })
        ]
      });
    }

    /** Family preview: light skin on the left half, dark on the right. */
    function FamilySwatch({ family }) {
      const light = family.skins.find((skin) => skin.colorScheme === "light");
      const dark = family.skins.find((skin) => skin.colorScheme === "dark");
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.splitSwatch,
        children: [
          (0, react_jsx_runtime.jsx)(SwatchHalf, { tokens: light.tokens }),
          (0, react_jsx_runtime.jsx)(SwatchHalf, { tokens: dark.tokens })
        ]
      });
    }

    /** "Default" chip: follow the built-in appearance (light + dark halves). */
    function DefaultSwatch() {
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.splitSwatch,
        children: [
          (0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#f4f4f5" } }),
          (0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#1c1c20" } })
        ]
      });
    }

    /** One selectable family card. */
    function FamilyCard({ family, selected, onSelect, t }) {
      return (0, react_jsx_runtime.jsxs)("button", {
        type: "button",
        onClick: (event) => {
          onSelect();
          // drop focus so a stale focus ring never outlives the selection
          event.currentTarget.blur();
        },
        "aria-pressed": selected,
        style: {
          ...styles.card,
          ...(selected ? styles.cardSelected : {})
        },
        children: [
          (0, react_jsx_runtime.jsx)(FamilySwatch, { family }),
          (0, react_jsx_runtime.jsx)("span", {
            style: {
              ...styles.cardLabel,
              ...(selected ? styles.cardLabelSelected : {})
            },
            children: t(`family.${family.id}`)
          })
        ]
      });
    }

    /** One mode chip (light / dark / system). */
    function ModeChip({ label, selected, onSelect }) {
      return (0, react_jsx_runtime.jsx)("button", {
        type: "button",
        onClick: (event) => {
          onSelect();
          event.currentTarget.blur();
        },
        "aria-pressed": selected,
        style: {
          ...styles.chip,
          ...(selected ? styles.chipSelected : {})
        },
        children: label
      });
    }

    /**
     * The pack's single settings row, registered into the Settings →
     * General item slot: a family card grid (Default + one per family)
     * and, once a family is chosen, a mode chip row (light / dark /
     * follow-system) plus a style chip row (minimal / vivid) that only
     * appears for families shipping more than one style.
     */
    function ThemeRow({ t, selectFamily, selectMode, selectStyle, useStore }) {
      const family = useStore((s) => s.family);
      const mode = useStore((s) => s.mode);
      const style = useStore((s) => s.style);
      const shippedStyles = family === null ? [] : familyStyles(family);
      return (0, react_jsx_runtime.jsxs)("div", {
        style: styles.group,
        children: [
          (0, react_jsx_runtime.jsx)("div", {
            style: styles.title,
            children: t("theme.title")
          }),
          (0, react_jsx_runtime.jsxs)("div", {
            style: styles.grid,
            children: [
              (0, react_jsx_runtime.jsxs)("button", {
                type: "button",
                onClick: (event) => {
                  selectFamily(null);
                  event.currentTarget.blur();
                },
                "aria-pressed": family === null,
                style: {
                  ...styles.card,
                  ...(family === null ? styles.cardSelected : {})
                },
                children: [
                  (0, react_jsx_runtime.jsx)(DefaultSwatch, {}),
                  (0, react_jsx_runtime.jsx)("span", {
                    style: {
                      ...styles.cardLabel,
                      ...(family === null ? styles.cardLabelSelected : {})
                    },
                    children: t("theme.default")
                  })
                ]
              }),
              CATALOG.map((familyDefinition) => (0, react_jsx_runtime.jsx)(FamilyCard, {
                family: familyDefinition,
                selected: family === familyDefinition.id,
                onSelect: () => selectFamily(familyDefinition.id),
                t
              }, familyDefinition.id))
            ]
          }),
          family === null
            ? null
            : (0, react_jsx_runtime.jsx)("div", {
                style: styles.chips,
                children: MODES.map((modeId) => (0, react_jsx_runtime.jsx)(ModeChip, {
                  label: t(`mode.${modeId}`),
                  selected: mode === modeId,
                  onSelect: () => selectMode(modeId)
                }, modeId))
              }),
          shippedStyles.length < 2
            ? null
            : (0, react_jsx_runtime.jsx)("div", {
                style: styles.chips,
                children: shippedStyles.map((styleId) => (0, react_jsx_runtime.jsx)(ModeChip, {
                  label: t(`style.${styleId}`),
                  selected: style === styleId,
                  onSelect: () => selectStyle(styleId)
                }, styleId))
              })
        ]
      });
    }
    //#endregion

    //#region dsh-themes: settings pal entry (vivid only)
    /**
     * CSS for the pal entry: keyframes and hover states can't be inline
     * styles, so the component carries one small <style> tag. It mounts
     * only while the entry renders — i.e. while a vivid pack skin with
     * pal images is active.
     */
    const PAL_CSS = `
.dsh-themes-pal { display: flex; align-items: center; gap: 8px; box-sizing: border-box; width: 100%; padding: 4px 8px; border: 0; background: transparent; cursor: pointer; font: inherit; border-radius: 10px; }
.dsh-themes-pal:hover { background: var(--dsw-alias-interactive-bg-hover); }
.dsh-themes-pal:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px; }
.dsh-themes-pal img { width: 56px; height: 56px; object-fit: contain; transform-origin: 50% 90%; }
.dsh-themes-pal:hover img { animation: dshThemesPalWiggle .45s ease; }
.dsh-themes-pal img.dsh-themes-pal-bounce { animation: dshThemesPalBounce .38s ease; }
.dsh-themes-pal-bubble { position: relative; padding: 4px 10px; border-radius: 12px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-pack-signature); font-size: 12px; line-height: 16px; white-space: nowrap; animation: dshThemesPalPop .22s ease; }
.dsh-themes-pal-bubble::before { content: ""; position: absolute; left: -4px; top: 50%; margin-top: -4px; border: 4px solid transparent; border-right-color: var(--dsw-alias-bg-layer-2); border-left: 0; }
@keyframes dshThemesPalWiggle { 0%, 100% { transform: rotate(0deg); } 25% { transform: rotate(-7deg) translateY(-2px); } 75% { transform: rotate(7deg) translateY(-2px); } }
@keyframes dshThemesPalBounce { 0% { transform: scale(1); } 30% { transform: scale(.82); } 62% { transform: scale(1.14) translateY(-4px); } 100% { transform: scale(1); } }
@keyframes dshThemesPalPop { 0% { opacity: 0; transform: scale(.6) translateY(4px); } 100% { opacity: 1; transform: scale(1) translateY(0); } }
`;

    /** Milliseconds the click animation plays before the settings panel opens. */
    const PAL_CLICK_DELAY = 380;

    /**
     * The vivid settings entry: one of the family's pal images plus a
     * character-voice speech bubble, sitting in the sidebar.footer.action
     * slot directly above the host settings trigger it replaces. Hover
     * wiggles the pal; a click bounces it, cycles to the next pal with
     * the next phrase, then forwards the click to the (hidden) host
     * trigger so the settings panel opens — the forward is a plain
     * timeout, so the panel opens even if animation events never fire.
     * Renders null outside the vivid style, leaving the host's own
     * settings button untouched.
     */
    function createPalEntry(ctx) {
      // The locale service's snapshot carries the active id ("zh"/"en") —
      // phrases follow the language picked in Settings → General.
      const readLang = () => (ctx.locale.getLocale()?.active === "zh" ? "zh" : "en");
      return function PalEntry({ wide }) {
        const [parsed, setParsed] = react.useState(() => parseSkin(ctx.theme.getTheme().preference));
        const [lang, setLang] = react.useState(readLang);
        const [palIndex, setPalIndex] = react.useState(0);
        const [phraseIndex, setPhraseIndex] = react.useState(0);
        const [bouncing, setBouncing] = react.useState(false);

        react.useEffect(() => ctx.on("theme/change", (snapshot) => setParsed(parseSkin(snapshot.preference))), []);
        react.useEffect(
          () => (typeof ctx.locale.subscribe === "function" ? ctx.locale.subscribe(() => setLang(readLang())) : undefined),
          []
        );

        const family = parsed === null ? null : CATALOG.find((entry) => entry.id === parsed.family);
        const pals = family?.decor?.pals ?? [];
        const visible = parsed !== null && parsed.style === "vivid" && pals.length > 0;

        // Stamp <body> once the host's settings trigger is confirmed in
        // the DOM; VIVID_RULES hides the trigger only under that
        // attribute, so the original button silently returns if the
        // anchor drifts. The trigger is rendered by another plugin and
        // may mount after us — poll briefly. The trigger button is
        // located by the slot container it hosts (data-slot
        // "settings.trigger"), the stable slot API the settings entry
        // uses — never by the CSS-module hash prefix, which shifts on
        // every harness build.
        react.useEffect(() => {
          if (!visible) return undefined;
          const triggerButton = () =>
            document.querySelector('[data-slot="settings.trigger"]')?.closest("button") ?? null;
          const stamp = () => {
            if (triggerButton() === null) return false;
            document.body.dataset.dshThemesPal = "";
            return true;
          };
          if (stamp()) return undefined;
          let tries = 0;
          const poll = setInterval(() => {
            tries += 1;
            if (stamp() || tries >= 20) clearInterval(poll);
          }, 300);
          return () => clearInterval(poll);
        }, [visible]);
        react.useEffect(
          () => () => {
            delete document.body.dataset.dshThemesPal;
          },
          []
        );

        if (!visible) return null;

        const phrases = family.decor?.phrases?.[lang] ?? family.decor?.phrases?.en ?? [];
        const phrase = phrases.length > 0 ? phrases[phraseIndex % phrases.length] : null;
        const pal = pals[palIndex % pals.length];

        return (0, react_jsx_runtime.jsxs)(react_jsx_runtime.Fragment, {
          children: [
            (0, react_jsx_runtime.jsx)("style", { children: PAL_CSS }),
            (0, react_jsx_runtime.jsxs)("button", {
              type: "button",
              className: "dsh-themes-pal",
              "aria-label": lang === "zh" ? "设置" : "Settings",
              onClick: (event) => {
                event.currentTarget.blur();
                setPalIndex((index) => index + 1);
                setPhraseIndex((index) => index + 1);
                setBouncing(true);
                setTimeout(() => setBouncing(false), PAL_CLICK_DELAY);
                // the animation must never gate the panel: the forward
                // fires on a plain timeout regardless of animation events
                setTimeout(() => {
                  document.querySelector('[data-slot="settings.trigger"]')?.closest("button")?.click();
                }, PAL_CLICK_DELAY);
              },
              children: [
                (0, react_jsx_runtime.jsx)("img", {
                  src: pal,
                  alt: "",
                  className: bouncing ? "dsh-themes-pal-bounce" : ""
                }),
                wide === false || phrase === null
                  ? null
                  : (0, react_jsx_runtime.jsx)("span", { className: "dsh-themes-pal-bubble", children: phrase }, phrase)
              ]
            })
          ]
        });
      };
    }
    //#endregion

    //#region dsh-themes: client plugin body
    /**
     * Required services: theme runtime (skins, switching), slots/locale
     * (the settings row). Persistence is localStorage, so no settings
     * transport is needed.
     */
    const inject = [
      "slots",
      "locale",
      "theme"
    ];

    /**
     * Client plugin body: register every skin into the theme runtime,
     * restore the saved meta preference (translating "system" against the
     * OS scheme and following its flips), keep the row's store in sync
     * with theme/change, and register the picker into Settings → General.
     * @param ctx - client cordis context.
     */
    function apply(ctx) {
      const disposers = SKINS.map((skinDefinition) => ctx.theme.register(skinDefinition));
      ctx.effect(() => () => {
        for (const dispose of disposers) dispose();
      }, "dsh-themes: theme registration");

      // Surface presence: the family palette must be visible in daily use,
      // not only in alerts. The user-message bubble carries a strong brand
      // wash; the sidebar's selected session takes the signature color;
      // the empty-workspace headline runs a brand → signature → warning
      // gradient. Message reference chips follow the brand. The rules
      // reference --dsw-pack-accent / --dsw-pack-signature, which every
      // skin in the pack defines, so they work unchanged for every family.
      // Keyed on stable CSS-module suffixes where possible.
      //
      // Every selector is boosted with :not(#dsh-themes): the shipped ui-*
      // stylesheets are injected by React after ours, so a plain attribute
      // selector loses to the equally specific module class and the tint
      // silently dies. The :not(id) pseudo is a no-op predicate that only
      // raises specificity.
      //
      // The sheet is mounted only while one of the pack's skins is active
      // and removed on the "Default" preference, so the built-in
      // appearance stays pixel-identical unless the user picked a family.
      // Hashed class suffixes can shift between harness versions — if one
      // stops matching, that accent silently falls back to neutral.
      const boost = (selector) =>
        selector.split(",").map((part) => `${part.trim()}:not(#dsh-themes)`).join(",");
      const SURFACE_RULES = [
        // user bubble: brand wash over the layer-2 surface, stronger on
        // dark skins where the ground is deep
        [
          '[class$="_userStack"] [class$="_bubble"]',
          " background: color-mix(in srgb, var(--dsw-pack-accent) 36%, var(--dsw-alias-bg-layer-2));"
        ],
        // body[data-ds-dark-theme] is present on dark schemes only: light
        // skins tint at 24% so the wash stays below the ink
        [
          'body:not([data-ds-dark-theme]) [class$="_userStack"] [class$="_bubble"]',
          " background: color-mix(in srgb, var(--dsw-pack-accent) 24%, var(--dsw-alias-bg-layer-2));"
        ],
        // message reference chips: recolor from the brand
        [
          '[class$="_refChip"]',
          " background: color-mix(in srgb, var(--dsw-alias-brand-primary) 22%, transparent);"
        ],
        // sidebar: the selected session's title carries the family's
        // signature color (gundam red, chainsaw blood red, …), other
        // titles warm to the brand on hover. CSS-module hash prefixes
        // shift per build; match the stable local suffixes only (the
        // host composes several classes on the row, so a single
        // ends-with can't see both — use contains for the row).
        [
          '[class*="_sessionRow"][class*="_selected"] [class$="_title"]',
          " color: var(--dsw-pack-signature);"
        ],
        [
          '[class*="_sessionRow"] [class$="_title"]:hover',
          " color: var(--dsw-pack-accent);"
        ],
        // message timestamps: a quiet signature accent
        [
          '[class$="_timeStart"]',
          " color: var(--dsw-pack-signature);"
        ],
        // empty-workspace headline: the family's full palette as a
        // brand → signature → warning gradient (gundam: blue → red →
        // gold; chainsaw: orange → blood → gold)
        [
          '[class$="_headlineText"]',
          [
            " background: linear-gradient(90deg, var(--dsw-pack-accent), var(--dsw-pack-signature), var(--dsw-alias-state-warn-primary));",
            " -webkit-background-clip: text;",
            " background-clip: text;",
            " -webkit-text-fill-color: transparent;",
            " color: transparent;"
          ].join("\n")
        ]
      ].map(([selector, body]) => `${boost(selector)} {\n${body}\n}`).join("\n");
      const style = document.createElement("style");
      style.textContent = SURFACE_RULES;

      // Vivid style, mounted only while a `*-vivid` skin is active. Where
      // the minimal style keeps the harness's restraint, vivid drops it:
      // tinted translucent papers and the brand sidebar come from the
      // skin's token overrides; this sheet adds what tokens cannot —
      // the transparent wallpaper watermark BEHIND the content (z-index
      // -1, bleeding through the 72%-opacity papers so it never covers
      // text), a big manga-panel scene occupying the right end of the
      // conversation header (painted as pseudos UNDER the header's own
      // children, so text and buttons stay on top and legible), a
      // tricolor strip across the top edge, solid-brand user
      // bubbles, and — on dark skins only, where the sidebar fill is a
      // deep brand color — light sidebar text. Light skins use a
      // mid-tint sidebar instead, where the global dark ink stays
      // readable without any overrides. All decorative layers are
      // pointer-events: none and never intercept clicks. Hashed class
      // prefixes can shift between harness versions — if one stops
      // matching, that accent falls back to neutral and nothing breaks.
      const vividEntry = ([selector, body, unboosted]) =>
        `${unboosted ? selector : boost(selector)} {\n${body}\n}`;
      const VIVID_RULES = [
        // solid ground under the translucent papers and the veil
        [
          "body",
          " background-color: var(--dsw-pack-paper);"
        ],
        // wallpaper veil behind the content: transparent cutout anchored
        // bottom-right, visible through the 72% papers and in margins
        [
          "#dsh-themes-veil",
          [
            " position: fixed;",
            " inset: 0;",
            " z-index: -1;",
            " pointer-events: none;",
            " background: var(--dsw-pack-wallpaper) no-repeat right bottom / min(42%, 560px);"
          ].join("\n"),
          true
        ],
        // the header decorations anchor to the title cluster — the
        // flex:1 box between the crumbs and the utilities — so the
        // artwork's right edge always sits just LEFT of the far-right
        // buttons (e.g. the "Session log" pill from session-log-export),
        // however wide that utilities box gets. It has no overflow of its
        // own; it only needs position: relative to anchor the pseudos.
        // Matched on the stable CSS-module local suffix `_titleCluster`
        // (the hash prefix shifts on every harness build).
        [
          '[class$="_titleCluster"]',
          " position: relative;"
        ],
        // header decoration, part 1: a signature-tinted color block
        // tucked behind the artwork's top corner (the panel's accent
        // chip — decorative blocks live in their own spots, away from
        // the text). Unboosted: boost() would append :not(#…) AFTER
        // the ::before pseudo-element, which is an invalid selector the
        // browser drops wholesale
        [
          '[class$="_titleCluster"]::before',
          [
            " content: \"\";",
            " position: absolute;",
            " top: -8px;",
            " right: 20px;",
            " width: 52px;",
            " height: 52px;",
            " border-radius: 14px;",
            " transform: rotate(10deg);",
            " background: color-mix(in srgb, var(--dsw-pack-signature) 22%, transparent);",
            " pointer-events: none;"
          ].join("\n"),
          true
        ],
        // header decoration, part 2: the manga-panel scene itself — a big
        // block filling the title cluster's right end. It overflows
        // DOWNWARD past the header's bottom edge into the content area
        // (popping upward gets clipped by an overflow:hidden ancestor
        // outside the header root); a mask fades the bottom edge so the
        // artwork melts into the chat instead of stamping over it. The
        // cluster's real children (crumbs, header actions) are hoisted to
        // z-index 1 ABOVE the two decorative pseudos, and the tabs row
        // carries its own z-index: 1 — text and buttons always render on
        // top, fully legible and clickable. Hidden on narrow windows
        // (media query appended below). Unboosted — same ::after reason
        // as part 1 above.
        [
          '[class$="_titleCluster"]::after',
          [
            " content: \"\";",
            " position: absolute;",
            " top: -10px;",
            " bottom: -60px;",
            " right: 4px;",
            " width: min(480px, 62%);",
            " background: var(--dsw-pack-panel) no-repeat right top / auto 100%;",
            " -webkit-mask-image: linear-gradient(#000 62%, transparent 96%);",
            " mask-image: linear-gradient(#000 62%, transparent 96%);",
            " pointer-events: none;"
          ].join("\n"),
          true
        ],
        // hoist the cluster's real children above the decorative pseudos
        [
          '[class$="_titleCluster"] > *',
          [
            " position: relative;",
            " z-index: 1;"
          ].join("\n"),
          true
        ],
        // the pal entry (sidebar.footer.action) replaces the host's
        // settings trigger. Hide the trigger only when the pal entry has
        // actually mounted AND located the trigger (it stamps
        // data-dsh-themes-pal on <body>) — if the anchor drifts in a
        // future harness build, the attribute is never set and the
        // original settings button simply stays visible. The trigger is
        // found via the slot container it hosts, never by its
        // CSS-module hash.
        [
          'body[data-dsh-themes-pal] button:has(> [data-slot="settings.trigger"])',
          " display: none;",
          true
        ],
        // tricolor strip across the top edge: brand → signature → gold
        [
          "#dsh-themes-strip",
          [
            " position: fixed;",
            " top: 0;",
            " left: 0;",
            " right: 0;",
            " height: 3px;",
            " z-index: 2147483647;",
            " pointer-events: none;",
            " background: linear-gradient(90deg, var(--dsw-pack-accent), var(--dsw-pack-signature), var(--dsw-pack-deep-accent));"
          ].join("\n"),
          true
        ],
        // top-left wordmark: a solid brand block behind the logo. The
        // BrandWordmark SVG paints in currentColor, so `color` recolors
        // it; brand/brand-text is the harness's own solid-button pair,
        // readable by construction on every skin. Contains-match on the
        // stable local suffix: the host composes the button's classes
        // (<hash>_brand <hash>_wide), so an ends-with selector on the
        // full class list never matches.
        [
          '[class$="_logoRow"] [class*="_brand"]',
          [
            " background: var(--dsw-alias-brand-primary);",
            " color: var(--dsw-alias-brand-text);",
            " border-radius: 10px;",
            " padding: 4px 12px;",
            " margin-right: 4px;"
          ].join("\n")
        ],
        // …but the wordmark's badge paths are NOT currentColor: they use
        // label-primary-inverted (paper-ish on both schemes) plus two
        // hardcoded whites, which on the brand block land within a few
        // points of the brand-text letters and swallow them. Sink those
        // fixed-color paths into the block's own brand color so only the
        // currentColor letters read.
        [
          '[class$="_logoRow"] [class*="_brand"] svg path:not([fill="none"]):not([fill="currentColor"])',
          " fill: var(--dsw-alias-brand-primary);"
        ],
        // user bubble goes solid brand with brand-on-brand text
        [
          '[class$="_userStack"] [class$="_bubble"]',
          [
            " background: var(--dsw-pack-accent);",
            " color: var(--dsw-alias-brand-text);"
          ].join("\n")
        ],
        // empty workspace (HeroShell): the wallpaper at FULL strength on
        // solid paper — this is the family's stage moment; the chat view
        // keeps the subtle bleed-through version. An opaque paper ground
        // under the artwork hides the behind-content veil here so the two
        // never double-print. Anchor on the stable local suffix `_root`
        // narrowed to the shell that contains the hero headline, so the
        // sidebar/session roots (which also end in `_root`) stay clean.
        [
          '[class$="_root"]:has([class$="_headlineText"])',
          [
            " background-color: var(--dsw-pack-paper);",
            " background-image: var(--dsw-pack-wallpaper);",
            " background-repeat: no-repeat;",
            " background-position: right 32px bottom 32px;",
            " background-size: min(36%, 460px);"
          ].join("\n")
        ],
        // project folder icons: themed artwork replacing the built-in
        // SVG, swapping closed → open via the row's aria-expanded (the
        // pack's little easter egg). The host hides this span on row
        // hover to show its chevron — that behavior is untouched.
        // Contains-match on `_folder` so the active row's extra
        // `_folderActive` class (the host composes several classes on
        // the icon) is matched too — ends-with would miss it.
        [
          '[class*="_folder"]',
          " background: var(--dsw-pack-folder) no-repeat center / contain;"
        ],
        [
          '[class*="_folder"] svg',
          " display: none;"
        ],
        [
          '[aria-expanded="true"] [class*="_folder"]',
          " background-image: var(--dsw-pack-folder-open);"
        ],
        // dark skins only: the sidebar fill is a deep brand color there,
        // so paint its text light with deep-accent gold for the selected
        // session and hover states
        [
          'body[data-ds-dark-theme] [class*="_sessionRow"] [class$="_title"]',
          " color: rgba(255, 255, 255, 0.92);"
        ],
        [
          'body[data-ds-dark-theme] [class*="_sessionRow"][class*="_selected"] [class$="_title"], body[data-ds-dark-theme] [class*="_sessionRow"] [class$="_title"]:hover',
          " color: var(--dsw-pack-deep-accent);"
        ],
        [
          'body[data-ds-dark-theme] [class*="_sessionRow"] [class$="_time"]',
          " color: rgba(255, 255, 255, 0.5);"
        ],
        [
          'body[data-ds-dark-theme] [class$="_newSessionLabel"], body[data-ds-dark-theme] [class$="_iconButton"], body[data-ds-dark-theme] [class$="_searchButton"]',
          " color: rgba(255, 255, 255, 0.78);"
        ],
        [
          'body[data-ds-dark-theme] [class$="_newSessionLabel"]:hover, body[data-ds-dark-theme] [class$="_iconButton"]:hover, body[data-ds-dark-theme] [class$="_searchButton"]:hover',
          " color: var(--dsw-pack-deep-accent);"
        ]
      ].map(vividEntry).join("\n") + "\n@media (max-width: 900px) {\n[class$=\"_titleCluster\"]::before, [class$=\"_titleCluster\"]::after { display: none; }\n}\n";
      const vividStyle = document.createElement("style");
      vividStyle.textContent = VIVID_RULES;
      const vividLayers = ["dsh-themes-veil", "dsh-themes-strip"].map((id) => {
        const div = document.createElement("div");
        div.id = id;
        div.setAttribute("aria-hidden", "true");
        return div;
      });
      const syncSurfaceTint = () => {
        const parsed = parseSkin(ctx.theme.getTheme().preference);
        const active = parsed !== null;
        const vivid = active && parsed.style === "vivid";
        if (active && !style.isConnected) document.head.appendChild(style);
        if (!active && style.isConnected) style.remove();
        if (vivid && !vividStyle.isConnected) document.head.appendChild(vividStyle);
        if (!vivid && vividStyle.isConnected) vividStyle.remove();
        for (const layer of vividLayers) {
          if (vivid && !layer.isConnected) document.body.appendChild(layer);
          if (!vivid && layer.isConnected) layer.remove();
        }
      };
      syncSurfaceTint();
      ctx.on("theme/change", syncSurfaceTint);
      ctx.effect(() => () => {
        style.remove();
        vividStyle.remove();
        for (const layer of vividLayers) layer.remove();
      }, "dsh-themes: surface tint lifecycle");

      // Restore the saved meta preference. The ThemeService adopts its
      // durable built-in preference ("light"/"dark"/"system") from the
      // Host settings scope asynchronously after boot, which overwrites a
      // third-party preference restored too early. Re-assert the resolved
      // skin for a short boot window (a handful of change events or a few
      // seconds), then yield to subsequent user actions.
      let bootGuard = readPref() ? 3 : 0;
      const reassertSaved = () => {
        if (bootGuard <= 0) return;
        const target = resolveSkin(readPref());
        if (target === null) return;
        if (ctx.theme.getTheme().preference === target) return;
        bootGuard -= 1;
        ctx.theme.setTheme(target);
      };
      reassertSaved();
      const bootWindow = setTimeout(() => {
        bootGuard = 0;
      }, 5000);
      ctx.effect(() => () => {
        clearTimeout(bootWindow);
      }, "dsh-themes: boot restore window");

      // Follow the OS color scheme while the stored mode is "system":
      // re-translate the meta preference into a concrete skin on every
      // flip. Explicit light/dark modes are pinned and ignore this.
      const onSchemeChange = () => {
        const stored = readPref();
        if (stored && stored.mode === "system") {
          ctx.theme.setTheme(resolveSkin(stored));
        }
      };
      darkQuery.addEventListener("change", onSchemeChange);
      ctx.effect(() => () => {
        darkQuery.removeEventListener("change", onSchemeChange);
      }, "dsh-themes: color-scheme listener");

      const prefStore = createPrefStore();
      let storeBound;
      const syncStore = (snapshot) => {
        const parsed = parseSkin(snapshot.preference);
        const stored = readPref();
        const sameFamily = parsed && stored && stored.family === parsed.family;
        const family = parsed ? parsed.family : null;
        const mode = parsed ? (sameFamily ? stored.mode : parsed.colorScheme) : "system";
        const style = parsed ? (sameFamily ? stored.style : parsed.style) : "minimal";
        storeBound?.sync(family, mode, style, snapshot.revision);
      };
      ctx.on("theme/change", (snapshot) => {
        const preference = snapshot.preference;
        const stored = readPref();
        const parsed = parseSkin(preference);
        if (parsed && preference !== resolveSkin(stored)) {
          // One of the pack's skins became active without matching the
          // stored meta preference (picked through another entry point):
          // adopt it as an explicit light/dark + style choice.
          writePref({ family: parsed.family, mode: parsed.colorScheme, style: parsed.style });
        } else if (!parsed && preference !== "light" && preference !== "dark" && preference !== "system") {
          // Another plugin's third-party theme took over: drop our stored
          // preference so only the last-picked plugin restores at boot
          // (both plugins must implement this convention).
          writePref(null);
        }
        syncStore(snapshot);
        // Re-assert from a fresh task: a re-entrant setTheme inside the
        // dispatch is missed by other subscribers (ui-layout's
        // ThemePresenter), so the restored skin would never reach the DOM.
        setTimeout(() => {
          reassertSaved();
        }, 0);
      });

      ctx.effect(() => ctx.locale.register(SETTINGS_NS, {
        zh,
        en
      }), "dsh-themes: settings row dictionaries");

      const themeInjected = (actions) => {
        storeBound = actions;
        syncStore(ctx.theme.getTheme());
        return {
          selectFamily: (familyId) => {
            if (familyId === null) {
              // Default: hand appearance back to the built-in light/dark/
              // system handling, natively following the OS.
              writePref(null);
              ctx.theme.setTheme("system");
              return;
            }
            // A freshly picked family starts in follow-system mode and
            // keeps the style it had when the family ships it, else falls
            // back to the family's first shipped style.
            const stored = readPref();
            const shipped = familyStyles(familyId);
            const keep = stored && stored.family === familyId;
            const pref = {
              family: familyId,
              mode: keep ? stored.mode : "system",
              style: keep && shipped.includes(stored.style) ? stored.style : shipped[0]
            };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          },
          selectMode: (mode) => {
            const stored = readPref();
            if (!stored) return;
            const pref = { family: stored.family, mode, style: stored.style };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          },
          selectStyle: (style) => {
            const stored = readPref();
            if (!stored) return;
            const pref = { family: stored.family, mode: stored.mode, style };
            writePref(pref);
            ctx.theme.setTheme(resolveSkin(pref));
          }
        };
      };
      ctx.slots.inject("settings.general.item", () => ctx.slots.register({
        name: "settings.general.item",
        id: "themes",
        order: 19,
        store: prefStore,
        locale: SETTINGS_NS,
        inject: themeInjected
      }, ThemeRow));

      // The vivid settings entry (pal images + character voice), seated
      // directly above the host settings trigger it replaces. The
      // component renders null outside the vivid style, so minimal skins
      // and the built-in appearance keep the stock settings button.
      ctx.slots.inject("sidebar.footer.action", () => ctx.slots.register({
        name: "sidebar.footer.action",
        id: "themes-pal",
        order: 19
      }, createPalEntry(ctx)));
    }
    //#endregion

    exports.CATALOG = CATALOG;
    exports.SKINS = SKINS;
    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
